### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by MikeRalphson** [openaustralia/morph#1003]
I suspect this may come under the heading of 'unsupported', but I'm trying to bring up a local copy of morph on Windows to try and submit a small PR or two. I don't expect to be able to run scrapers without docker, but it would be nice to be able to authenticate and access all parts of the app.

It works so far up until the point the github auth redirect comes back, but 

http://127.0.0.1:3000/users/auth/github/callback?code={code}&state={state}

Doesn't generate any response. What I have in the log is:

````
=> Booting Puma
=> Rails 4.1.14.1 application starting in test on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
d:/nodejs/morph/app/models/scraper.rb:44: warning: duplicated key at line 45 ignored: :if
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: test
* Listening on tcp://0.0.0.0:3000
I, [2016-05-06T15:16:51.770330 #1544]  INFO -- omniauth: (github) Request phase initiated.
I, [2016-05-06T15:16:58.036848 #1544]  INFO -- omniauth: (github) Callback phase initiated.
I, [2016-05-06T15:16:58.248865 #1544]  INFO -- omniauth: (github) Callback phase initiated.
I, [2016-05-06T15:16:58.332873 #1544]  INFO -- omniauth: (github) Callback phase initiated.
````

I'm starting the app with `rails server` as foreman appears to have some problems on Windows and the supposed fix hasn't been merged yet.

I've configured .env and the github app as per the README.md, and I can see one user has been authorised on the github side.

Is there somewhere I can start digging as to why the app isn't creating the user (there are no rows in `owners`) and/or redirecting? 

Some of the steps I went through to get this far are on a [wiki page](https://github.com/openaustralia/morph/wiki/Windows-install-instructions)

**Comment by henare** [comment]
You're a brave person indeed @MikeRalphson :smile: Yes, I think this will have to come under "unsupported" and wontfix, sorry.

However have you tried to run morph.io under a virtual machine? There's even a Vagrantfile - it is designed for bringing up a complete production copy but with a bit of hacking could be limited to just creating a development machine.

If you need help with that please don't hesitate to [ask in the forum](https://help.morph.io/) and I'll try to help where I can.
