### ISSUE TITLE
Data table UI

### ISSUE THREAD

**Issue by wfdd** [openaustralia/morph#1005]
It's not obvious the data table will only ever show the first ten records.  When I see 'rows 10 / 189', I'd almost certainly expect there to be a button to skip to the next page.

**Comment by henare** [comment]
I think this would be covered by #97 so I'll close this as a duplicate. Thanks for reporting it @wfdd :sparkles:

**Comment by wfdd** [comment]
If #97 isn't in the pipeline, it might be worth rephrasing the label now to something that doesn't resemble pagination, e.g. '189 rows (only showing first 10)'.
