### ISSUE TITLE
Write blog post about starting stability & scalability work on morph.io

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#1011]
Because it's a good thing to let people know that we care! :-)

**Comment by henare** [comment]
Woohoo! @mlandauer do you think we could aim to publish this week?

**Comment by mlandauer** [comment]
I'll try to get something done this week but I can't promise...

**Comment by mlandauer** [comment]
Done. Post is here: https://www.openaustraliafoundation.org.au/2016/07/07/matthews-back-improving-the-stability-and-scalability-of-the-morph-io-platform/

**Comment by henare** [comment]
We should email this out to morph.io users too. I'll reopen this to remind us to do that.

**Comment by henare** [comment]
Sent :email:
