### ISSUE TITLE
Encourage concurrency in docs

### ISSUE THREAD

**Issue by wfdd** [openaustralia/morph#1016]
Scraping is generally I/O-bound, so it might make sense to instruct people to use an event loop or multi-processing or what-have-you to speed up their scrapers, and therefore also freeing up the task queue.  For comparison, https://morph.io/wfdd/colombia-senado-scraper, which issues about 200 requests runs in less than a minute, whereas https://morph.io/tmtmtmtm/colombia-representantes, which scrapes 167 pages in total, takes 8 minutes to complete.

**Comment by wfdd** [comment]
On the flipside, it'd also need to come with a giant warning not to flood other people's servers with tens and hundreds of simultaneous requests....

**Comment by tmtmtmtm** [comment]
Generally we don't mind if scrapers run slowly (at least at the level of taking 10 minutes vs 1). They're essentially a background job running at unpredictable times anyway, and as you say it's a lot nicer on the remote server.

**Comment by wfdd** [comment]
I don't have a clear picture of the architecture, but I was under the impression there was a limit on how many of these jobs can run in parallel.  By 'we' do you mean Morph or EveryPolitician?

**Comment by tmtmtmtm** [comment]
'we' there was EveryPolitician. Morph is Someone Else's Problem :)

**Comment by wfdd** [comment]
Oh alright.  Well, I didn't think it'd be an issue for EP.

[For me, I've got the bad habit of using the inclusive 'we' wherever I comment on GitHub.  I probably offended someone, somewhere, at some point.]

**Comment by wfdd** [comment]
Judging from the emoji 'responses' above there's no interest, so closing.
