### ISSUE TITLE
Scraper stuck

### ISSUE THREAD

**Issue by wfdd** [openaustralia/morph#1020]
Looks like [this](https://morph.io/wfdd/bahamas-parliament-scraper) one's been 'injecting and compiling' for about 11 hours now.  I could restart but I thought you might want to investigate.

**Comment by henare** [comment]
Thanks @wfdd. I'm assigning this to @mlandauer because he's looking at this type of thing at the moment.

**Comment by mlandauer** [comment]
Sorry I didn't get a chance to look at this but it seems to be okay now as far as I can tell. Closing
