### ISSUE TITLE
free text search for scrapers & authors

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#103]
Could be by name, description, author, code, urls scraped (see #47)

**Comment by equivalentideas** [comment]
This would be very useful, I was just trying to see if a scraper existed, but no obvious way to search.

**Comment by mlandauer** [comment]
As @henare just pointed out to me this is really important and has been sadly neglected and is really quite important as there are SO MANY SCRAPERS now ;-)

**Comment by mlandauer** [comment]
Added a super-basic search that just searches over the scraper name and description. I'll split the rest of the suggested functionality of this issue into separate issues.
