### ISSUE TITLE
Set noeviction policy on redis

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#1056]
See https://github.com/mperham/sidekiq/wiki/Using-Redis#memory

It looks like the fact that we don't have this setup would explain some of the situations as to why we have lost jobs on the queue

**Comment by mlandauer** [comment]
The noeviction policy goes hand in hand with the setting of memory limit. It would be good to do this to ensure that redis doesn't get normally restarted by monit

**Comment by auxesis** [comment]
👍  to setting a Redis memory limit coupled with `maxmemory-policy noeviction`. 

Given the disk space issues Morph is having at the moment, you should seriously consider disabling [the RDB snapshotting](https://github.com/openaustralia/morph/blob/d3fa58994959a5d16fb81405f280afafcc2eb464/provisioning/roles/redis/files/redis.conf#L144-L146). This would turn Redis into a purely ephemeral data store with no persistence. 

Per [Redis Persistence](https://redis.io/topics/persistence#rdb-disadvantages) documentation:

> RDB needs to fork() often in order to persist on disk using a child process. Fork() can be time consuming if the dataset is big, and may result in Redis to stop serving clients for some millisecond or even for one second if the dataset is very big and the CPU performance not great. AOF also needs to fork() but you can tune how often you want to rewrite your logs without any trade-off on durability.

The impact on the Morph box is: 

- CPU performance will spike whenever Redis is flushing data to disk
- Memory usage and disk usage balloons whenever a `fork()` happens

We'd need to do a bit more research to work out what impact disabling data persistence has on Sidekiq, but from memory it should be OK. 

Regardless of whether you disable the RDB snapshotting entirely, setting a memory limit in Redis will give you known limits on the amount of disk space you will need to run Redis for Morph. This is extremely helpful for capacity planning and monitoring.

**Comment by equivalentideas** [comment]
I think this is [causing the problem](https://github.com/openaustralia/morph/issues/1050#issuecomment-277894267) which just resulted in 116 scrapers being stuck for a week.

**Comment by henare** [comment]
>This would turn Redis into a purely ephemeral data store with no persistence.

That's the opposite of what we want to do. As per the Sidekiq documentation linked above:

>Many people use Redis as a cache but it's important that Sidekiq be run against a Redis instance that is not configured as a cache but as a persistent store.

We want to make sure that Redis is a **persistent store so we don't lose jobs off the queue**. We think it's the most likely reason that [jobs disappear off the queue](https://github.com/openaustralia/morph/issues/1098).

**Comment by henare** [comment]
>Regardless of whether you disable the RDB snapshotting entirely, setting a memory limit in Redis will give you known limits on the amount of disk space you will need to run Redis for Morph. This is extremely helpful for capacity planning and monitoring.

I think the memory used by Redis would be minimal. Even when the queue backs up we typically only have about 1,000 jobs waiting and I doubt they'd take much space - a few megabytes? Right now the queue is in its typical state, a few jobs running and about 1,200 scheduled and it's snapshot is 335K on disk.

I'm not sure what Matthew meant here:

>The noeviction policy goes hand in hand with the setting of memory limit. It would be good to do this to ensure that redis doesn't get normally restarted by monit

Apart from a memory leak once we've never had probems with Redis and memory and it wasn't being managed by monit. However Sidekiq was managed by monit so maybe that's what he meant? I certainly think it's a good idea to fix up monit's management of Sidekiq (it's broken right now AFAIK).
