### ISSUE TITLE
Reduce size of production server when possible

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#1062]
Once we've done the postgres migration and any other things required to keep disk space under control we should reduce the size of the server again. Otherwise it will end up costing a lot of money each month

**Comment by henare** [comment]
We'll have to remember to reduce the number of concurrent containers then too. At the moment it's specced to be able to run however many 512MB containers simultaneously.

**Comment by mlandauer** [comment]
I haven't changed the number of concurrent containers after just upgrading the server, so as long as that remains the case we shouldn't have to change the number of concurrent containers when we downgrade the server

**Comment by mlandauer** [comment]
I had to resize the disk back down to 392,960 MB (= 768GB / 2 - 256 MB), then migrate to the smaller plan which took about half an hour for each operation. Now, after the move to the smaller disk we are now at 54% full. Pretty good!

This was obviously only possible after doing a bunch of work to clear disk space before the migration back to the small production server
