### ISSUE TITLE
can't delete scrapers

### ISSUE THREAD

**Issue by davidmarin** [openaustralia/morph#1085]
I'm trying to delete my [msd](https://morph.io/spendright/msd) and [scrape-urls](https://morph.io/spendright/scrape-urls) scrapers, but when I try, I get a "We're sorry, but something went wrong" message.

**Comment by henare** [comment]
@davidmarin thanks for reporting this. I'll close this as it's a duplicate of #1084.

**Comment by davidmarin** [comment]
Thanks! Sorry to go, but an in-house strategy (using git-controlled YAML files) seems to be a better fit for what I'm doing.
