### ISSUE TITLE
Can't delete scraper

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#1089]
From https://morph.io/tmtmtmtm/chile-congress-wikidata/settings, if I try to delete the scraper, I get the "We're sorry, but something went wrong. If you are the application owner check the logs for more information" error.

Not sure if this is the same as #1084. It's also possible that this is because the underlying git repo has been transferred.

**Comment by henare** [comment]
I've just checked Honeybadger and I can confirm it's the same issue as #1084 so I'll close this as a duplicate.
