### ISSUE TITLE
scrapper creation stuck at "creating GitHub repo"

### ISSUE THREAD

**Issue by hanecak** [openaustralia/morph#1103]
I've tried creating a scraper from scratch, but it got stuck at "createing GitBub repository", see:

- https://morph.io/OpenDataSk/siemens-sk-utilities-scraper
- https://morph.io/soit-sk/siemens-sk-utilities-scraper

In the man time, I've succeed but now I would like to clean-up the mess (deleting OpenDataSk entry and making soit-sk entry working).

Can you please provide assistance by deleting the two linked scrapers? I will then re-create the right one. Thank you in advance.

**Comment by equivalentideas** [comment]
Hi @hanecak Thanks for reporting this. I've deleted both those scrapers.

**Comment by hanecak** [comment]
I've recreated https://morph.io/soit-sk/siemens-sk-utilities-scraper, thank you very much.

Side observation: GitHib repo syncing (while adding existing scraper) took quite long (several minutes) but at the end succeeded.
