### ISSUE TITLE
Multiple pages throwing 500s

### ISSUE THREAD

**Issue by tatey** [openaustralia/morph#1106]
Hello,

As of 8:50AM on Sun 15 Jan UTC+10 the following pages are throwing 500s:

* https://morph.io/tatey
* https://morph.io/explore
* https://morph.io/tatey/new-zealand-radio-spectrum-licenses

My suspicion is that any page which has my scraper https://morph.io/tatey/new-zealand-radio-spectrum-licenses throws an exception. I pushed to the repo and ran the scraper for the first time around 10:10 PM on Sat 14 Jan UTC+10. I can run the scraper locally on my computer.

Without access to exception I can't work out what's going on. I tried searching for issues with the `bug` label but didn't see anything obvious. Are exceptions automatically created as issues, or is there a manual trigger from honeybadger by one of the project maintainers?

Thanks a tonne for building the project. I think it's a neat idea which is why I'm so keen to build a scraper 😄

**Comment by tatey** [comment]
FYI pages are now OK around 9:45PM on Sun 15 Jan UTC+10.

**Comment by henare** [comment]
@tatey this was probably a disk space problem. Glad to hear everything's working again :sunny:

**Comment by tatey** [comment]
Appreciate the reply. Thanks.
