### ISSUE TITLE
Profile doesn't show, returns "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by nickjevershed** [openaustralia/morph#1111]
Profile: [https://morph.io/nickjevershed](https://morph.io/nickjevershed)

Error message on opening: 
> 
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

**Comment by equivalentideas** [comment]
Hey @nickjevershed thanks for letting us know about this 👍 that was related to [disk space issues we're having at the moment](https://github.com/openaustralia/morph/issues/1104). You can access it again now. Let us know if this happens again, but probably no need for an issue. Just ping @openaustralia on twitter or Slack, or post in the help forum.

**Comment by nickjevershed** [comment]
Thanks @equivalentideas, I thought I should check in case I'd broken something :P
