### ISSUE TITLE
morph.io has fallen over, badly

### ISSUE THREAD

**Issue by chris48s** [openaustralia/morph#1129]
Website has been dark since Friday night:
http://graphs.morph.io/dashboard/db/morph?from=now-7d&to=now

**Comment by henare** [comment]
@chris48s Thanks for your patience. According to the Linode dashboard the CPUs were pegged at 100%. I restarted the server using their console and I've been poking an prodding at the queue throughout the day to clear things up. When I first booted the server we had over 1,000 jobs queued and that's now down to 330. Hopefully that will be cleared in a couple of hours and things will be back to normal.

**Comment by chris48s** [comment]
thanks :+1:
