### ISSUE TITLE
Scraper contributors not updated

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#1147]
This scraper [lists 1 contributor](https://morph.io/planningalerts-scrapers/logan) when [there are 2](https://github.com/planningalerts-scrapers/logan/graphs/contributors).

**Comment by LoveMyData** [comment]
It is showing three contributors on the mentioned [scraper ](https://morph.io/planningalerts-scrapers/logan)

![image](https://user-images.githubusercontent.com/15683093/31208453-c23c3fcc-a9d0-11e7-8678-1375f3f143b8.png)

**Comment by henare** [comment]
Closing as cannot reproduce in that case :smile:
