### ISSUE TITLE
Support any programming language by using Dockerfiles

### ISSUE THREAD

**Issue by sixcorners** [openaustralia/morph#1149]
If scrapers could use Dockerfiles (or you just ran public images on docker hub) then any language could be used to write a scraper. If the contract is just that the scraper needs to put a sqlite database somewhere it seems like this could be easy to implement.

**Comment by equivalentideas** [comment]
Thanks @sixcorners 👍 This seems potentially related to https://github.com/openaustralia/morph/issues/647 ?

**Comment by mlandauer** [comment]
Thanks @sixcorners for your suggestion.

We'll definitely be sticking with the buildpack based approach. We're not a general hosting solution so I don't see much value in going with allowing people to use any old docker image. It also would make things harder to support. So, I'll close this as a "won't fix".

@sixcorners if you have any other suggestions please let us know.

**Comment by mlandauer** [comment]
@sixcorners is there a specific language that is currently not supported by morph.io that you would like to use? It might actually be pretty straightforward to add with buildpacks as most languages are already supported we just haven't necessarily added their support to morph.io.
