### ISSUE TITLE
All my (python) scrapers are failing with `requests.exceptions.ConnectionError`

### ISSUE THREAD

**Issue by andylolz** [openaustralia/morph#1164]
The error looks like this:

```
requests.exceptions.ConnectionError:
HTTPConnectionPool(host='www.example.com', port=80): Max retries exceeded with
url: / (Caused by
NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection
object at 0x7ff7eec059e8>: Failed to establish a new connection: [Errno 111]
Connection refused',))
```

Apologies if this is the wrong place to report this! Thanks

**Comment by andylolz** [comment]
Looks like 1559/1765 = 89% of auto-running scrapers are failing. my guess is the other scrapers aren’t making any requests.

**Comment by mlandauer** [comment]
I'm investigating...

**Comment by mlandauer** [comment]
Thanks for reporting this! @andylolz the problem should be resolved now. I'm going to close this but please do reopen it if you see that it hasn't gone away.

**Comment by andylolz** [comment]
Thanks @mlandauer! :tada:
