### ISSUE TITLE
Large amount of PHP scrapers are receiving error message

### ISSUE THREAD

**Issue by LoveMyData** [openaustralia/morph#1165]
```
Injecting configuration and compiling...
 [1G       [1G-----> PHP app detected
 [1G-----> Bootstrapping...
 [91m
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[0m
```
Examples:
https://morph.io/LoveMyData/greatlakes
https://morph.io/LoveMyData/georges_river
https://morph.io/LoveMyData/bogan
https://morph.io/LoveMyData/saplanningportal
https://morph.io/LoveMyData/ballina_shire

**Comment by mlandauer** [comment]
As mentioned in Slack I can reproduce the problem on a local development morph instance so thankfully it has nothing to do with the setup of the new morph server.

**Comment by mlandauer** [comment]
@LoveMyData It's not deployed to production yet. I'll let you know here when that's done.

**Comment by mlandauer** [comment]
@LoveMyData this is now deployed to production
