### ISSUE TITLE
morph.io website is very slow to load

### ISSUE THREAD

**Issue by LoveMyData** [openaustralia/morph#1167]
the web site easily take 30 plus seconds to load in a browser.

**Comment by LoveMyData** [comment]
Looks like once I am logged against github. morph is doing something to behind like check what scraper is not working etc hence added the delay.

If i open morph.io in incognito mode, morph.io is pretty quick to load.

**Comment by henare** [comment]
I'm not even able to access the site in private browsing. When I first tried I got this error:

![screenshot from 2017-12-13 14-16-11](https://user-images.githubusercontent.com/48945/33920145-7c6dc878-e010-11e7-96c2-2bf01551562e.png)

Now I'm getting no response at all. http://downforeveryoneorjustme.com/morph.io says,

> It's not just you! morph.io looks down from here.

**Comment by mlandauer** [comment]
A few speed optimisations have been made in 628d6194cb7b09c4456626d7c877673aeb7d8aad, fa603afbb2cc452dbd00305b2355f1391a81dc71, 157528bb1796c6d0a48f532575e63ff98542be83 and 5a47b48f798ffb2b8cec83130c63e9eea6e48f07.

These speed up the home page (when logged in), user or organisation pages with lots of scrapers (like  https://morph.io/planningalerts-scrapers/) and scraper pages with lots of runs on them.

The pages don't exactly load super fast now but they're not like craaazzy long anymore. I do think that the site overall needs a lot more work to make it feel really speedy again (like in the good old days) but i think the current fixes are good enough to at least close this ticket.
