### ISSUE TITLE
API responds with wrong MIME type (application/json, not application/javascript)

### ISSUE THREAD

**Issue by andylolz** [openaustralia/morph#1176]
Reposting from https://github.com/openaustralia/morph/issues/371#issuecomment-368476295, because that issue is old & closed. I use the API over javascript a lot, and it’s currently broken in Chrome.

---

I’m using the javascript example (in the browser) on the API page, and hitting the following error:

> Refused to execute script from '[URL]' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

The same code previously worked fine. Would the MIME type of the response have changed for some reason?

**Comment by mlandauer** [comment]
@andylolz oops. sorry. that's more than likely my fault as yesterday I started doing some emergency work on the scraper data api to improve its memory profile. So, I probably broke this. I'll look at this a bit later today...

**Comment by andylolz** [comment]
Great! Thanks @mlandauer

**Comment by mlandauer** [comment]
that's deployed to production so should be hopefully back to normal. @andylolz please do let me know if you see anything else amiss. Thanks for reporting the problem.

**Comment by andylolz** [comment]
Looks good to me. Thanks for fixing so promptly!

**Comment by andylolz** [comment]
Looks good to me. Thanks for addressing this so promptly!
