### ISSUE TITLE
Put some vanity (social validation) stats on the home page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#119]
... web pages scraped
... rows of data created
by ... users

**Comment by mlandauer** [comment]
Now that mitmproxy is a step closer we can put the number of web pages scraped in the last week which will be a fairly large number

**Comment by mlandauer** [comment]
@equivalentideas do you think it's worth throwing this ticket into the mix for the first pass of the landing page?

**Comment by equivalentideas** [comment]
@mlandauer I don’t think so actually. It's probably something we want to do early in the next stage when we're looking at what the compelling data and activity in the side is—but I don't think it should hold up getting the new homepage deployed. How does that sound?

**Comment by mlandauer** [comment]
Sounds good to me. A related question, is the new milestone you made for new home page for the first stage (the quick win) or for anything up to the more involved work through of the home page?

**Comment by equivalentideas** [comment]
I recon we just use it for the initial quick win for logged out users. Then we can make a new one for the next stage. There is a few dup-ish issues in there because some of them are more broad ideas, maybe we should pull those out and focus on specific to-dos to get the new version ready to deploy.

**Comment by equivalentideas** [comment]
From chat with @mlandauer:

This is about demonstrating the *scale of activity* on morph.io to validate and reenforce that morph is awesome and they should give it a go or explore it.

We've decided to focus on three pieces of data that tell the story of how morph is being used:

* number of pages scraped
* number of rows of data created
* number of downloads (includes API queries)

We're also thinking we'll show the *stats for this weeks* so it's very clear this is all happening right now. People's scrapers are churning away, giving them the data they need, and they're using it right now.

**Comment by equivalentideas** [comment]
Here's a sketch of what this could be like:

![img_3793](https://cloud.githubusercontent.com/assets/1239550/7720284/d1f65b60-ff0e-11e4-92cd-1623e963f2cf.jpg)

Text:

* 22,000 web pages scraped
* 750,000 rows of data created
* 5,000 downloads and API queries

I'm not sure about data created or data collected. I think maybe collected is fits the mental model of scraping more.

I think we use 'downloads and API queries' rather than just 'downloads' to reinforce that it's getting used in apps and that we provide nice apis.

Any thoughts on this @mlandauer ?

I tried an idea of having two blocks:

* 38,000 web pages turned into 750,000 rows of data
* 5,000 downloads and API queries

But it didn't work, I think the three distinct stages tells a clearer story.

**Comment by equivalentideas** [comment]
I'm thinking about where this should go in the order on the landing page.

**Comment by equivalentideas** [comment]
I'm feeling like right down the bottom, after the quotes makes sense. It's after the more human story of the important things people are doing with morph.io. Then as a powerful full stop: by the way, people are collecting and using a massive amount of data with this right now.

**Comment by mlandauer** [comment]
:+1: all looks good to me!

**Comment by equivalentideas** [comment]
> :+1: all looks good to me!

Ok cool, I'll move on to doing to implementing the static version of this. @mlandauer do you have any idea of what those numbers will be?

**Comment by mlandauer** [comment]
@equivalentideas no. sorry.

**Comment by equivalentideas** [comment]
:) no worries, I'm interested to find out!

**Comment by equivalentideas** [comment]
Basic version on the page:

![screen shot 2015-05-20 at 5 37 18 pm](https://cloud.githubusercontent.com/assets/1239550/7721041/f4aa104a-ff16-11e4-9b1b-e13353be7187.png)

**Comment by mlandauer** [comment]
Looking good!

**Comment by equivalentideas** [comment]
A left aligned version is also quite smart, but I think that's a slight departure from the current landing page style and we should stick with centred. Leaving this here as a note for the future:

![screen shot 2015-05-20 at 5 59 44 pm](https://cloud.githubusercontent.com/assets/1239550/7721341/3af9c20e-ff1a-11e4-9215-160b14ffc6ef.png)
![screen shot 2015-05-20 at 6 00 47 pm](https://cloud.githubusercontent.com/assets/1239550/7721342/3afdcf5c-ff1a-11e4-8000-9c030350b681.png)

Need to try a few things to make this sit a bit more nicely beneath the slightly nasty active scrapers column on the signed in version:

![screen shot 2015-05-20 at 6 04 17 pm](https://cloud.githubusercontent.com/assets/1239550/7721414/c1b1d4d0-ff1a-11e4-9141-cf1e0e75db09.png)

**Comment by mlandauer** [comment]
I've got some code nearly ready to calculate the stats so as soon as you can do a PR for the static version I can get that stuff in there ;-)

**Comment by equivalentideas** [comment]
I think we need to have 'This week on morph.io' so it's always clear what this is.

**Comment by equivalentideas** [comment]
I think 'This week *at* morph.io' rather than '*on* morph.io'. Refer to it as a place where things are happening, rather than like a TV show or something "Last week on Game of Thrones" :P

**Comment by mlandauer** [comment]
I think that's good ;-)

**Comment by equivalentideas** [comment]
![screen shot 2015-05-20 at 6 34 37 pm](https://cloud.githubusercontent.com/assets/1239550/7721909/f6fc4c70-ff1e-11e4-91d1-b786bf7def90.png)

So we always remember where morph was today ;)
