### ISSUE TITLE
No data showing in API feed

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/morph#1224]
https://help.morph.io/t/api-atom-feed-is-no-longer-generating-correctly/567

>The API atom feed is no longer generating correctly, the feed appears empty.
>
>This has been the case since around 1st July 2019, impacting all my scrapers.

Confirmed with:

https://api.morph.io/Kooben209/OT-PP/data.atom?key=XXXXXXXXXXXXXXXX&query=select%20address%20%7C%7C%20price%20as%20content%2C%20title%20as%20title%2C%20link%20as%20link%2C%20pubdate%20as%20date%20from%20%22otmdata%22%20limit%2010

**Comment by mlandauer** [comment]
It looks there was a morph deploy on the 1st of July. So, maybe something there broke it. I will investigate.

**Comment by mlandauer** [comment]
This is what changed in that deploy of 1st of July: https://help.morph.io/t/api-atom-feed-is-no-longer-generating-correctly/567 - quite a lot, then as we added rubocop and made lots of fixes. So that certainly looks like the culprit.

**Comment by mlandauer** [comment]
I tested the atom feed on my local development version of morph.io (which is currently sitting at origin/master 96d62e183f89b2fa1a3fad1cc772a9da4246ade9) and I can't reproduce the problem. It worked fine for me. I'll test the same thing out in production now.

**Comment by mlandauer** [comment]
I've confirmed production is sitting at the same revision.

**Comment by mlandauer** [comment]
Again I can't reproduce the problem in production looking at a planningalerts scraper. The url I tried was https://api.morph.io/planningalerts-scrapers/multiple_masterview/data.atom?key=xxxxxxxxxxxxxxxxxxxx&query=select%20address%20as%20title%2C%20description%20as%20content%2C%20info_url%20as%20link%2C%20date_scraped%20as%20date%20from%20%22data%22%20limit%2010

**Comment by mlandauer** [comment]
Okay I *can* reproduce it in production on the specific scraper https://morph.io/Kooben209/OT-PP/ - the csv and json appears to work but not the atom. Now, to try to reproduce the problem locally...

**Comment by mlandauer** [comment]
This is now deployed to production and have confirmed that this all looks fixed now.
