### ISSUE TITLE
All systems critical!

### ISSUE THREAD

**Issue by layday** [openaustralia/morph#1227]
It would seem all queued scrapers are stuck and when I try to log into my account, I get:

> We're sorry, but something went wrong.
>
> If you are the application owner check the logs for more information.

(which means I couldn't post about this on your discourse)

**Comment by mlandauer** [comment]
Thanks @layday for letting us know. We're investigating right now.

**Comment by layday** [comment]
Looks like everything's back on track.  Thanks for your work on morph.
