### ISSUE TITLE
remove link to waffle.io on morph.io

### ISSUE THREAD

**Issue by katska** [openaustralia/morph#1240]
Remove the link to waffle.io. This link is broken because waffle.io no longer exists.
Reported as
"I noticed that you have a broken link to a website called Waffle.io. That site was first published way back in 2013 but unfortunately, it is no longer a working website.

You link to Waffle.io on this page: https://morph.io/"

**Comment by mlandauer** [comment]
Ooh. That's not good.

**Comment by mlandauer** [comment]
Fixed by aee91307f13878c6415234da8cfca53d7812ad46
