### ISSUE TITLE
morph.io is down

### ISSUE THREAD

**Issue by jasonchanhku** [openaustralia/morph#1246]
Hi there,

I noticed that the website https://morph.io/ has been down for sometime. 

![image](https://user-images.githubusercontent.com/20807220/102680637-07e25b00-41f5-11eb-9c5a-250fe838c26a.png)

First and foremost I really appreciate what you guys do and thank you for everything. May I know what's the estimated downtime and current status? Thanks.

**Comment by dcalde** [comment]
is there any update on this? the site appears to be more down than up.
