### ISSUE TITLE
Unable to login to Morph

### ISSUE THREAD

**Issue by ineffyble** [openaustralia/morph#1269]
Trying to login to morph.io for the first time.

After proceeding with the GitHub OAuth prompt I get `Could not authenticate you from GitHub because "Invalid credentials".`:

![image](https://user-images.githubusercontent.com/834880/132604113-46a5f2a4-fa74-47c1-a884-1e44bde8f5db.png)

**Comment by dcalde** [comment]
I am having the same issue. Not sure if related, but I have MFA enabled on my Github account.

**Comment by 0pete** [comment]
Same error and I also have MFA enabled on my Github account.

**Comment by dcalde** [comment]
Thanks @mlandauer

**Comment by mlandauer** [comment]
Thanks @ineffyble @dcalde @peterherrmann for reporting the problem! And thanks for using morph.io :-)
