### ISSUE TITLE
Creating new Scraper stuck in Phase "Add Scraper template ..."

### ISSUE THREAD

**Issue by BernhardKoehler** [openaustralia/morph#1283]
Hello,
I am new with morph.io and first wanted to create a new scraper here. I started with [https://morph.io/BernhardKoehler/TVScraper](https://morph.io/BernhardKoehler/TVScraper) but it gets stuck in the phase "Add Scraper template ...". What did I do wrong?
For testing if it was only a single problem with the one scraper I started, I started a new Scraper [https://morph.io/BernhardKoehler/Test](https://morph.io/BernhardKoehler/Test) wich also gets stuck in the same phase.
Please help. Thank you.
Best regards 
Bernhard Koehler

**Comment by mlandauer** [comment]
Fixed now. Sorry it took so long

**Comment by BernhardKoehler** [comment]
@mlandauer Thank you, but what exactly have you fixed? When i call my scrapers (as in the links above) they still are in phase "Add Scraper template ...".
Should I do something now to go ahead with it?
Thank you
Best regards 
Bernhard Koehler
