### ISSUE TITLE
Delete profile for user with closed GitHub account

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/morph#1331]
I have received a message on social media asking if it’s possible to delete https://morph.io/rob-tolan

The person is unable to do this themselves as the GitHub account associated with the Morph profile has been deleted.

**Comment by benrfairless** [comment]
@mlandauer @katska I’ll send you the details of the person on Twitter shortly 😊

**Comment by katska** [comment]
@benrfairless thanks so much for following up, you're a star! I've had a look but I don't seem to have options/permissions to action editing users. @mlandauer please can you up my permissions on morph or delete this person's record  https://morph.io/rob-tolan from morph.io ?

**Comment by mlandauer** [comment]
Done. If you follow the link above you can see it 404s now.

**Comment by katska** [comment]
@mlandauer thank you!
