### ISSUE TITLE
Install iconv locales for PHP

### ISSUE THREAD

**Issue by hannesgassert** [openaustralia/morph#206]
The example in http://www.php.net/manual/en/function.iconv.php#105507 prints questions marks instead of correct transliterations ("Gödel" turns into "G?del" instead of "Goedel"), which is a sign of missing locale data. Would be very useful to sanitize international data.

Herzlichen Dank! :)

**Comment by mlandauer** [comment]
I don't think this has been an issue for a long time. Quite a long time ago there was an issue where console log output wasn't always being interpreted as utf-8. That is long fixed so as far as I'm aware this problem isn't around anymore. Please do reopen this issue with some more info if that isn't the case.
