### ISSUE TITLE
Create an About Page

### ISSUE THREAD

**Issue by kat** [openaustralia/morph#225]
About Page
Some suggested wording for an 'about page'.

Writing and running a scraper yourself is something that any capable developer can do without Morph. With Morph it’s fun and easy.

Morph is a scraping platform built around GitHub. 

GitHub has become the de-facto way that open source software developers collaborate. They truly have nailed the solution with pull requests, their issue system, commenting on code, and social discovery through starring repositories and more.

Morph leverages those tools and integrate them very tightly to become a way of using Github but that’s specialised towards scrapers. 

to edit, at https://docs.google.com/a/oaf.org.au/document/d/11UvNkLeYVXt_Yh0KoIO7aHHIIFwO8knMfNFk81fhOCU/edit

**Comment by mlandauer** [comment]
I'm happy not having an about page for the time being
