### ISSUE TITLE
Set up a root logger for languages that permit doing so

### ISSUE THREAD

**Issue by mdanielwork** [openaustralia/morph#229]
This is similar to #125 but slightly different; in Python it is possible to configure the `logging` system using code, a file or even over a socket(!). I suspect there are similar mechanisms available to Ruby and PHP.

This has the advantage of the "morph container" controlling where (and in what format) the log entries are emitted, but allows the script to choose the log level (e.g. put in lots of `logging.debug` but only set the logging level to `DEBUG` during development).

Print statements are the path to the dark side.

But I agree with the author of 125; please capture the output and make it available because we have no debugger available.

**Comment by mlandauer** [comment]
For simplicity sake we're going to stick with logging to standard out with errors going to standard error all of which are shown in the console log in the morph ui. If you want to control the level of output you can certainly do that in the application with any of the languages in the current setup.
