### ISSUE TITLE
Add specific examples in how to use the API for different languages

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#255]
Do this for Ruby, PHP, Python, commandline(curl) and javascript including ajax. For example
```
$.ajax({
    url : "AJAX_GET_URL",
    type: "GET",
    data: { 'query': QUERY_TO_EXECUTE},
    headers: {'x-api-header': APIKEY},
    success: function(data, textStatus, jqXHR)
    {
        //data - response from server
    },
    error: function (jqXHR, textStatus, errorThrown)
    {

    }
});
```

**Comment by equivalentideas** [comment]
From dupe #717 :

As a user without experience using api's, when I want to use scraped data via the JSON API, give me an example of making a basic query in the language I write, to save me time and help me build what I want.

This weekend I started on a small rails app that uses morph.io data via a json api. It took me a bit of research to find a clear answer on what the simplest way to make an API request and read the JSON data. I was excited to use the data, but this slowed me down and was frustrating. I think this is a roadblock that many users may face, that morph could help with.

Potential solution: On the api docs page provide examples of making simple api requests in a few key languages.

**Comment by mlandauer** [comment]
Added examples for ruby and javascript to documentation. I think we should add Python as well but that isn't there yet.

**Comment by mlandauer** [comment]
There are now example for using curl, javascript, python and ruby
