### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by hailspuds** [openaustralia/morph#257]
I ran into this problem again:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

URL here: https://morph.io/hailspuds/foi-disclog-comms

Steps:
1) Added scraper from GitHub
2) Ran it (it errored - something to do with rb.php)
3) Ran again (because the error is fixed when you run a second time when the sqlite database is created) 

Then I got that error.
Sorry about this happening again. I'm not sure what I did wrong...

**Comment by PuZZleDucK** [comment]
I think I've done a similar thing here: https://morph.io/PuZZleDucK/rockingham-node

After reading this thread I cleared the DB and the page works fine, but after running scraper the page errors until I delete the DB or scraper (at that point is says the scraper ran ok and 2 records were added)... Is there something I can do on my end?

**Comment by equivalentideas** [comment]
@PuZZleDucK Thanks for raising this. Currently your scraper is totally inaccessible for some reason. I've raise an issue to try and get to the bottom of it here https://github.com/openaustralia/morph/issues/1115

**Comment by equivalentideas** [comment]
@PuZZleDucK that bug has now been fixed by @henare with https://github.com/openaustralia/morph/pull/1116 you can now get to your scraper to see if that problem is still happening :)

**Comment by equivalentideas** [comment]
@PuZZleDucK that bug has now been fixed by @henare with https://github.com/openaustralia/morph/pull/1116 you can now get to your scraper to see if that problem is still happening :)
