### ISSUE TITLE
Make user/org display more graphical on home page

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#325]
Use nice big avatars instead of the username text heavy version we have now. Think of GitHub's team member display for inspiration.

The text is noisy and doesn't add much value - how often does the text help over the avatar? However the avatar display is visually interesting and makes it more personal ("all these people are using Morph!").

**Comment by mlandauer** [comment]
Put a graphical list of "featured" orgs on the marketing page would be really nice too because it shows how civic tech organisations are using scrapers to do practical stuff and it's a bit of social validation too.

**Comment by henare** [comment]
This is no longer relevant with the new home page so closing.

>Put a graphical list of "featured" orgs on the marketing page would be really nice too because it shows how civic tech organisations are using scrapers to do practical stuff and it's a bit of social validation too.

This should be extracted into its own issue if it's something we still want to do.
