### ISSUE TITLE
NoMethodError - undefined method `new_session_path' for #<Users::OmniauthCallbacksController:0x...>

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#347]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://www.honeybadger.io/inspector/p/35868/4813964)

**Comment by mlandauer** [comment]
I can't even reproduce this problem locally. I've tried using my local dev morph through incognito mode with javascript disabled. I log in via github. I put in my github username and password and then it gives me a page with only one button. There is no way to reject the permissions other than just to navigate away.

So, I'm a bit confused what might be going on here. Is this maybe not a problem anymore?

**Comment by bbqsrc** [comment]
Disable cookies, not javascript.

**Comment by mlandauer** [comment]
@bbqsrc thanks!

**Comment by mlandauer** [comment]
Thanks @bbqsrc. I can now reproduce the problem locally by disabling cookies globally but specifically allowing cookies for github.com. This way, the github side of the oauth sign in works but it only fails when it comes back to morph

**Comment by mlandauer** [comment]
Going with this solution: https://github.com/plataformatec/devise/wiki/OmniAuth%3A-Overview#using-omniauth-without-other-authentications
