### ISSUE TITLE
Octokit::Unauthorized - GET https://api.github.com/user/emails: 401 - Requires authentication // See: https://developer.github.com/v3

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#366]
## Backtrace

    line 68 of [PROJECT_ROOT]/lib/morph/github.rb: emails
    line 61 of [PROJECT_ROOT]/lib/morph/github.rb: primary_email
    line 120 of [PROJECT_ROOT]/app/models/user.rb: refresh_info_from_github!
    line 127 of [PROJECT_ROOT]/app/models/user.rb: find_or_create_by_nickname
    line 64 of [PROJECT_ROOT]/app/models/scraper.rb: block in update_contributors
    line 63 of [PROJECT_ROOT]/app/models/scraper.rb: map
    line 63 of [PROJECT_ROOT]/app/models/scraper.rb: update_contributors
    line 289 of [PROJECT_ROOT]/app/models/scraper.rb: synchronise_repo
    line 7 of [PROJECT_ROOT]/app/workers/create_from_github_worker.rb: perform

[View full backtrace and more info at honeybadger.io](https://www.honeybadger.io/inspector/p/35868/5266966)

**Comment by mlandauer** [comment]
Haven't seen this issue in a long time. So, closing.
