### ISSUE TITLE
Save data to Github

### ISSUE THREAD

**Issue by sabas** [openaustralia/morph#368]
Add some way to push scraped data to the scraper repository, like a csv in a data/ folder.

Is #159 solved? I couldn't find a way to see the changes of the data today..

It could be done via github itself, pushing each run to the same file (but there's a file size limit) and then linking to the diff.

**Comment by henare** [comment]
You could use the GitHub API to push data to your repo, storing GitHub credentials as [secret values](https://morph.io/documentation/secret_values). If you need a hand with that ask away over at the [help forum](https://help.morph.io/).

However I don't see us building this into morph.io so I'm going to close this as wontfix for now.
