### ISSUE TITLE
Support JSONP in Chrome

### ISSUE THREAD

**Issue by sabas** [openaustralia/morph#371]
Chrome has security policies which block jsonp if there isn't the correct header set.
`Refused to execute script from '[URL]' because its MIME type ('application/json')
is not executable, and strict MIME type checking is enabled.`

(from #255)

**Comment by andylolz** [comment]
I’m using the javascript example (in the browser) on the API page, and hitting the same error:

> Refused to execute script from '[URL]' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

The same code previously worked fine. Would the MIME type of the response have changed for some reason?
