### ISSUE TITLE
prompt description for new scrapers

### ISSUE THREAD

**Issue by kat** [openaustralia/morph#385]
When someone adds a new scraper, ask the user "what does your scraper do?" to the description field, so that others might find useful scrapers more easily.

**Comment by equivalentideas** [comment]
Adding a new scraper process reminded me of how nasty this is currently.

We could add 'What will this scraper do?' as part of the label, and then provide an example of a good description.

**Comment by mlandauer** [comment]
:+1:

**Comment by equivalentideas** [comment]
This is what the current input looks like:

![screen shot 2015-05-06 at 6 56 58 pm](https://cloud.githubusercontent.com/assets/1239550/7490205/b93dc7ea-f421-11e4-8de0-ddbdcf623306.png)

**Comment by equivalentideas** [comment]
What's an example of a good description that we'd like people create? We can use that to design for that outcome.

Here are some that I think are quite good examples:

> Scraper that gets MP's details from APH.gov.au for OpenAustralia.org

> City of Gold Coast Development Applications

> New North Warwickshire Food Safety Inspections

> Excused absence requests of Slovak parliament members

Each of these you can understand what the scraper gets from the description. One of them says what the scraper is for as well—I'm not sure if that's helpful or not.

They say specifically what the data is and who/where does it relate to.

Good tips:

Use key words like country, location, institution or name of the data source.

Try and imagine what you would put in a search engine to find this data (they've probably just done this) and make sure you include those terms.
