### ISSUE TITLE
Not enough memory to parse a page with BeautifulSoup

### ISSUE THREAD

**Issue by spendright-scrapers** [openaustralia/morph#387]
I have a parser for the [HRC Buyer's Guide](http://www.hrc.org/apps/buyersguide/) and other consumer campaigns, which is [here](https://morph.io/spendright-scrapers/campaigns) on morph.io.

It works great, except when I try to parse [the Food & Beverages category page](http://www.hrc.org/apps/buyersguide/ranking.php?category=1223), my scraper dies with status 137 (i.e. it was `kill -9`ed). I assume a supervisor process decided it exceeded its memory limitations?

I did a little testing, and it happens when I parse the page with `BeautifulSoup`. Here's some equivalent code that should cause the same problem:

```python
from bs4 import BeautifulSoup
import scraperwiki

html = scraperwiki.scrape('http://www.hrc.org/apps/buyersguide/ranking.php?category=1223')
# so far so good
soup = BeautifulSoup(html)
# process died with status 137
```

Is there any way you can up the memory limit? In theory, I could rewrite this as some sort of SAX parser or something, but it'd slow me down.

Currently working around this by using an environment variable to disable scraping this one page.

**Comment by mlandauer** [comment]
@spendright-scrapers are you still experiencing this issue? I'm going to close it based on the assumption that you're not. If you are still seeing this do please reopen the issue

**Comment by davidmarin** [comment]
Confirmed, this issue has gone away.
