### ISSUE TITLE
NoMethodError - undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#388]
@dannycheeseman's scraper is stuck creating: https://morph.io/dannycheeseman/gumtree_test

## Backtrace

[View full backtrace and more info at honeybadger.io](https://www.honeybadger.io/inspector/p/35868/4813964)

**Comment by henare** [comment]
Fixed in b88db19be60c550e13b48b0de6a9aeffd04bb41d
