### ISSUE TITLE
Orgs not refreshed

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#397]
The GH orgs are never refreshed. This means that I can't create scrapers under @morph-test-scrapers because I've only recently been added to it :(

**Comment by mlandauer** [comment]
Orgs that you are a member of are now refreshed if you log out and log back in. Also, there is a rake task for updating all the orgs.

It's a bit hacky but I think it's "good enough" for now

**Comment by jfilter** [comment]
Logging in & out does not refresh my org list :/
