### ISSUE TITLE
With finished run don't include compile output by default

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#405]
It would be nice if you could optionally show the compile output too

**Comment by mlandauer** [comment]
Related to #401

@henare @equivalentideas FYI I'm getting close to nailing the rest of the outstanding bugs related to morph buildpacks. It would be great to get everyone moved on to buildpacks by default as soon as is practical.

This issue is one of the outstanding ones that requires a little more thought.

So far with buildpacks we've been showing the compile output which is useful to see, especially if you make a mistake in one of your config files (like `Gemfile` for ruby).

However, it also exposes some of the underlying mechanics of the docker stuff which could very easily be super-confusing for a new-comer.

So, it would be good to figure out how to deal with this.

My thought so far is we intelligently show or hide the compiler output depending on the situation and make it clear in the UI that it's different than the scraper console log.

Your thoughts/ideas appreciated!

**Comment by henare** [comment]
Travis does some nice folding/hiding or verbose unnecessary output - maybe look there for inspiration?

**Comment by equivalentideas** [comment]
We could add a checkbox above saving 'show compiler output' or something that fits developer's mental model, like in the Chrome browser console it has '[ ] hide network messages'.

I've never used buildpacks or seen that output so I'm a bit unclear on the usecase.

**Comment by mlandauer** [comment]
I'm going to close this as "won't fix" because the compile step output is now drastically simpler. If we feel at a later stage that this is still necessary we can just reopen this issue or create a new one
