### ISSUE TITLE
replace morph logo section on homepage with introductory text

### ISSUE THREAD

**Issue by kat** [openaustralia/morph#416]
also see #211

**Comment by equivalentideas** [comment]
I'm not sure what this one means @kat If this is still an issue could you add a description and screenshot?

**Comment by kat** [comment]
not an issue when [the sheepy version](https://github.com/openaustralia/morph/tree/new_landing_page), is rolled out - this is however still what's currently visible over at morph.io

**Comment by mlandauer** [comment]
Okay, I'll close this then
