### ISSUE TITLE
add quotes from external users

### ISSUE THREAD

**Issue by kat** [openaustralia/morph#417]
Rather than all OAF quotes, it would be great to have one or two supporting quotes from external users on the front page.

**Comment by equivalentideas** [comment]
I think it would be good to use these great quotes that demonstrate the features through use.

from @rezzo 

> Scrapers are kept in public github repos and then we consume the data from an API, delicious! Is like scrapers with steroids!

and a chopped down version of @hailspuds 

> I love Morph because it gives you everything you need to run a scraper. I've written a system which notifies me when Australian FOI disclosure logs are updated.

**Comment by equivalentideas** [comment]
@hailspuds do you mind if we use your full name?

or maybe the morph user names is better?

**Comment by hailspuds** [comment]
I don't mind at all if you want to use my full name. 

If you'd prefer github name though, I'm happy with that too. Either or!

(It'll spur me on to fix the scrapers too!)

**Comment by equivalentideas** [comment]
Closed by https://github.com/openaustralia/morph/commit/a6286c2b201cd181238d6889b67a621668d196a0

Thanks for the quotes!
