### ISSUE TITLE
add contact address @morph.io 

### ISSUE THREAD

**Issue by kat** [openaustralia/morph#418]
Create a contact address for morph.io (currently contact@oaf.org.au) & update contact info footer on morph.io

**Comment by mlandauer** [comment]
I think we've been doing fine by just having the contact address be contact@oaf.org.au. For the audience of this app we don't need to "hide" the fact that it's run by OAF

**Comment by kat** [comment]
Is there a way to ensure you can detect the morph emails when they arrive then?

**Comment by mlandauer** [comment]
@kat how do you mean? Do you mean ensuring that they get answered? That's another problem that I think we have with all our contact emails. Shall we say that's an "unsolved problem"?

**Comment by kat** [comment]
for filtering/triage. I filter them all by the to field into project folders and check those folders periodically for queries. If there is another way to ID the mails  on this subject as they come in maybe that's ok for OAF purposes. I do also think its easier for users to remember a morph.io address if they're using morph.io, but I can understand if you're a bit over having so many addresses to manage.
