### ISSUE TITLE
scrapper being killed by SIGKILL

### ISSUE THREAD

**Issue by lkundrak** [openaustralia/morph#423]
https://morph.io/soit-sk/bratislava_faktury

My scraper receives SIGKILL, despite running fine on my machine and I can't figure out why. I suspected it could be due to resource consumption -- on my x86_64 lappy it seems to max at ~420MB or memory.

I believe it used to run correctly (I've deleted it since, as it couldn't be stopped - issue #415) and changes I've made shouldn't have influenced the memory consumption significantly.

Also, sometimes it seems to finishes successfully, but leaves nothing in database. I suspect it's killed as well, only error is left unnoticed for some reason. Not sure though.

**Comment by mlandauer** [comment]
At the moment scrapers are limited to 100MB of memory and will be automatically killed if they go over that limit. As this ticket is quite old I'm closing it. If you have a more recent issue please either reopen this issue or create a new one.

Thanks!
