### ISSUE TITLE
Container compile bugs mean scrapers keep retrying

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#432]
This scraper https://morph.io/planningalerts-scrapers/development_assessment_panel_applications is affected by #430.

When it runs the error `Errno::ENOENT: No such file or directory - /tmp/morph20140721-29398-1tiive8/ruby_pdf_helper/.git` gets raised in the background queue and the queue just keeps retrying it.

**Comment by mlandauer** [comment]
I haven't seen this in a while and should only happen if there's a bug in the compile step. So, closing
