### ISSUE TITLE
How to get data from another scraper?

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#436]
When I try to fetch over the API (with my API_KEY in an ENV variable) — such as in https://github.com/tmtmtmtm/publicwhip_policies/commit/b92313db9bb647b07fe8da04760a5eb4217a5d10 — I get an error:

    /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/openssl/ssl-internal.rb:121:in `post_connection_check': hostname was not match with the server certificate (OpenSSL::SSL::SSLError)

[and fetching over plain http: doesn't work, as it simply issues a redirect to https:]

I can work around this with an explicit:

    open(url, {ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE}).read

but that seems wrong. Is there a better way of using the data from another scraper?

**Comment by henare** [comment]
This seems to work now: https://morph.io/morph-test-scrapers/morph_api

Please reopen if it's still an issue.

**Comment by tmtmtmtm** [comment]
Thanks!
