### ISSUE TITLE
Clicking on a scraper with missing repo 404s

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#439]
The changes added in #438 mean that if a scraper has a missing repo, and you're not the owner, when you click on the scraper it 404s. This is unexpected, the user shouldn't see the scraper at all.

If you're the owner you're redirected to the settings page, told about the issue, and given the opportunity to delete and recreate it or contact us.

**Comment by mlandauer** [comment]
I haven't seen this in ages. @henare do you know if this is still happening?

**Comment by henare** [comment]
I don't know. It should be easy to test.

**Comment by mlandauer** [comment]
I'm just going to close this
