### ISSUE TITLE
GitHub organisation support

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#44]
So that if you're a member of an organisation and have commit rights to a repo you can add and control a scraper

**Comment by jmatsushita** [comment]
Hi there, I'm afraid I don't understand how support for organisations work. I've authorized access to all my organisation repos when signing up. But for instance https://morph.io/iilab goes to a 404. I can't find an option in my profile and when trying to import scrapers I can only see my personal gihub repos and not my organisations. (might be in the help site but its down #868 )

**Comment by equivalentideas** [comment]
Hi @jmatsushita , sorry that the help forum is down, we've got our server goblins working on it.

Is your membership of the organisations on github public? I can't see any public orgs on your github profile. Private organisation memberships don't show up in morph.io.
