### ISSUE TITLE
Show featured scrapers on home page

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#448]
When you first find a project like morph.io it's common to want to see an example quickly to help you understand what this thing is.

On projects like ours you can simply check public examples which is great. However there's often heaps of poor examples, e.g. broken demo scrapers, so it would be really helpful to feature high quality, useful examples.

Right now we could just do this manually but you could also do it programmatically, e.g. most visited public projects, most accessed via the API, most linked to, etc.

**Comment by mlandauer** [comment]
A first pass of hand curated scrapers is now listed on the new landing page. So, let's call this done for the time being
