### ISSUE TITLE
Scraper doesn't save results in the db

### ISSUE THREAD

**Issue by sabas** [openaustralia/morph#453]
I am trying to understand why my scraper doesn't add any data to the db, and I would like to ask for advice..
Here it is https://github.com/sabas/catalogo-nazionale-programmi-riusabili/blob/master/scraper.php the data is produced but it isn't saved.
Here's a screenshot of part of last local execution (I managed to run scraperwiki php locally, resulted a 200 rows array)
![image](https://cloud.githubusercontent.com/assets/1304918/4250853/d7d3da68-3a87-11e4-9d95-1a0f4ab4ea3b.png)

Could you give me some hints?
Thanks

**Comment by mlandauer** [comment]
Hi @sabas - it looks like the sqlite database was messed up in some way. I fixed that and everything looks to be working now: https://morph.io/sabas/catalogo-nazionale-programmi-riusabili

The scraper ran successfully and saved the data in the database as it should have. All it needed was to go Settings/Clear Database.

**Comment by sabas** [comment]
Nice, thanks!
