### ISSUE TITLE
Git submodules cause problems

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#456]
https://github.com/spendright-scrapers/companies

`Errno::ENOENT - No such file or directory - /var/www/releases/20140920073127/db/scrapers/repos/spendright-scrapers/companies/srs`

## Backtrace

    line 231 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: read
    line 231 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: block in all_hash
    line 224 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: all_hash
    line 216 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: all_config_hash
    line 192 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: all_config_hash_with_defaults
    line 130 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: tar_config_files
    line 84 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: compile
    line 93 of [PROJECT_ROOT]/lib/morph/container_compiler.rb: compile_and_run_with_buildpacks
    line 115 of [PROJECT_ROOT]/app/models/run.rb: go_with_logging
    line 175 of [PROJECT_ROOT]/app/models/run.rb: go!
    line 185 of [PROJECT_ROOT]/app/models/run.rb: synch_and_go!
    line 5 of [PROJECT_ROOT]/app/workers/run_worker.rb: perform

[View full backtrace and more info at honeybadger.io](https://www.honeybadger.io/projects/35868/faults/8437341)

**Comment by davidmarin** [comment]
@henare, any progress on this? SpendRight is using Python 3 internally, and it would be nice to update our scrapers as well.

**Comment by henare** [comment]
@davidmarin this issue is not something I'm actively working on, sorry.

**Comment by davidmarin** [comment]
No worries! Thanks for your honesty.

**Comment by mlandauer** [comment]
@davidmarin I've been doing some major work on the buildpack support recently including fixing a long-standing permissions issue which was probably at the root of some of the problems you experienced before when you switched to buildpacks.

This is all with the aim of getting buildpacks to the stage where we can switch everyone over to it seamlessly.

I'd be very keen on you trying buildpacks again with the incentive for you being that you can use Python 3, if you're up for it?

Let me know if you'd like me to reenable buildpacks for @spendright-scrapers

**Comment by mlandauer** [comment]
I'm going to close this issue. Please reopen it, or create a new issue if you experience this problem again

**Comment by spendright-scrapers** [comment]
@mlandauer, sure, let's give it a try! Would love to get my entire codebase on Python 3 eventually (though that will mean porting `dumptruck` as well).

Also, I've been wondering how you set up scrapers for an organization (e.g. `openaustralia`). Ideally, I'd like the main repo for these scrapers to be under the `spendright` organization on GitHub.

**Comment by mlandauer** [comment]
@spendright-scrapers I've enabled buildpacks on https://morph.io/spendright-scrapers so now all scrapers running under https://morph.io/spendright-scrapers will use buildpacks automatically.

To set up an organization, go to github and set up an organization there, make yourself a public member of that organization.

The only hassle right now is for morph.io to pick that up you might need to log out and log back in on morph. Then, you should see your membership of that organization on your user page on morph https://morph.io/spendright-scrapers.

Then, you can create scrapers under your organization in exactly the same way. Anyone that you make a public member of the organization will be able to do the same.

Hope that helps.

**Comment by spendright-scrapers** [comment]
@mlandauer Thanks!

Unfortunately, it looks like my scrapers still totally don't work with buildpacks (the symptom is that they can't import code from the `srs` submodule, I think same as last time). Can you please switch me back off buildpacks until the submodule issue is resolved?

The console *does* work a lot better with buildpacks now; nice!

**Comment by mlandauer** [comment]
@spendright-scrapers I'll switch off buildpacks for you right away. Could you possibly write some minimal test code that shows the problem you're seeing so I can reproduce it at my end?

**Comment by mlandauer** [comment]
@spendright-scrapers buildpack stuff switch off for you now

**Comment by mlandauer** [comment]
@spendright-scrapers sorry. don't worry about the minimal test code for the moment. I'll start by forking your scraper `spendright-scrapers/companies` and check that I can reproduce the problem

**Comment by mlandauer** [comment]
@spendright-scrapers I can reproduce the problem locally so that's most of the battle over. Now to fix it!

**Comment by mlandauer** [comment]
Part of the issue here is that only certain files from your repo are injected into the scraper container during the "compile" phase where it parses `requirements.txt` and `runtime.txt` to install the libraries and the right version of python.

So, it doesn't at this stage have access to the submodule just your `requirements.txt` file in the root of the directory.

This is what I tried.

First, installing `srs` directly from git by putting this in `requirements.txt`:
```
git+http://github.com/spendright-scrapers/srs.git@e3b09f6#egg=srs
```

This avoids the need for submodules.

But this ends up not installing the libraries in the `requirements.txt` file inside `srs`. My understanding of `pip` is a bit limited so I'm not sure why that's happening.

So then just to see what would happen I added the contents of the `srs` requirements file to the main requirements file to give:
```
git+http://github.com/spendright-scrapers/srs.git@e3b09f6#egg=srs
Unidecode==0.04.9
beautifulsoup4==4.1.3
dumptruck==0.1.6
html5lib==0.90  # used by beautifulsoup4
requests==1.0.4  # used by srs.vendor.reppy
```

This now gives the following error when you run the scraper:
```
Traceback (most recent call last):
  File "scraper.py", line 26, in <module>
    from srs.db import use_decimal_type_in_sqlite
  File "/app/.heroku/python/lib/python2.7/site-packages/srs/db.py", line 12, in <module>
     from .scrape import download
  File "/app/.heroku/python/lib/python2.7/site-packages/srs/scrape.py", line 16, in <module>
    from .vendor.reppy.cache import RobotsCache
ImportError: No module named vendor.reppy.cache
```

@spendright What shall I try next?

**Comment by mlandauer** [comment]
I've discovered that another issue is that symbolic links are not getting injected into the container when it injects the source of the repo. This issue is in #562

**Comment by spendright-scrapers** [comment]
Awesome, thanks, go for it!

I have my own poor-man's version of morph.io in production, so it's not the end of the world if my scrapers are broken on morph.io. I just don't have the spare cycles to poke at it and try to make it work right now.

**Comment by mlandauer** [comment]
I'm reopening until we know that this is definitely fixed

**Comment by mlandauer** [comment]
After you merged the PR I've switched buildpacks back on for you @spendright-scrapers @davidmarin. Hopefully the scraper for you now works with buildpacks. If you do have another issue don't hesitate to open another ticket here. Thanks!
