### ISSUE TITLE
buildpack scraper appears to never finish

### ISSUE THREAD

**Issue by spendright-scrapers** [openaustralia/morph#458]
My [companies](https://morph.io/spendright-scrapers/companies) scraper, which runs in less than three minutes on my local machine (and ran fine before buildpacks were enabled) has been "running" now for about 30 minutes. Can anyone explain what's going on?

**Comment by mlandauer** [comment]
It looks to me like the [companies](https://morph.io/spendright-scrapers/companies) scraper has been running successfully. So, I'm closing this ticket.

@spendright-scrapers if things are still an issue, please reopen the ticket!

**Comment by spendright-scrapers** [comment]
@mlandauer it's only working because I asked for experimental buildpacks to be disabled on my account.

**Comment by mlandauer** [comment]
@spendright-scrapers I recently upgraded the buildpack infrastructure which also fixed a long-standing file permissions mismatch between the buildpack and non-buildpack scrapers. This might have been the underlying cause of some of the problems you were having with buildpacks.

Would you be willing to give buildpacks another go? If so let me know and I'll enable them again for you
