### ISSUE TITLE
perl WWW::Mechanize is missing

### ISSUE THREAD

**Issue by katkad** [openaustralia/morph#459]
with WWW::Mechanize perl people are able to click, and find all links and inputs according to regexp

https://morph.io/soit-sk/dusevne_vlastnictvo
https://morph.io/soit-sk/vyberove_konania_ms_sr

**Comment by mlandauer** [comment]
@katkad these days we're putting most of our effort into getting the [buildpack support](https://morph.io/documentation/buildpacks) working as smoothly as possible. Buildpacks allow you to install whatever libraries you want very easily.

Let me know if you would like buildpack support enabled for your account so you can try it out

**Comment by katkad** [comment]
No thanks. When buildpack support was enabled, lot of our scrappers stalled.
