### ISSUE TITLE
Enable memory limit support

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#461]
I think that memory limitations on our Docker containers aren't being enforced, which is causing the server crashing problem we've intermittently been having. Behold the WARNINGs we get when running `docker` commands (last two lines here):

```
deploy@localhost:/var/docker$ docker info
Containers: 235
Images: 196
Storage Driver: devicemapper
 Pool Name: docker-202:0-170135-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 15.57 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 29.61 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.16.5-x86_64-linode46
Operating System: Ubuntu precise (12.04.5 LTS)
WARNING: No memory limit support
WARNING: No swap limit support
deploy@localhost:/var/docker$ 
```

>If you want to enable memory and swap accounting, you must add the following command-line parameters to your kernel...

http://docs.docker.com/installation/ubuntulinux/#memory-and-swap-accounting

**Comment by mlandauer** [comment]
Curious. I made the necessary changes on my local vm (via ansible) and "docker info" doesn't return the warning anymore.

However, when I made the changes to production (and reboot) it's still showing the warnings in "docker info"...

**Comment by mlandauer** [comment]
Not fixed yet unfortunately

**Comment by mlandauer** [comment]
It looks like this is more complicated on linode. Have put in a support question to double check if my understanding is correct

**Comment by mlandauer** [comment]
So, yes, according to support we do need to run a custom kernel to make the changes we want to make on linode. I'll experiment with another machine on linode. It does seem worth the effort, as much pain as it is, to improve stability

**Comment by mlandauer** [comment]
These are the instructions to follow: https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub

**Comment by mlandauer** [comment]
Updates made via ansible provisioning. Now

```
root@li421-88:~# docker info
Containers: 1
Images: 73
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 4
Total Memory: 3.907 GiB
Name: li421-88
ID: CL77:IFT2:ANFR:PBLJ:7BZN:2CSP:SLZ6:IZVC:VFV2:BLUL:TSMD:NHLA
```
