### ISSUE TITLE
Start Discourse on boot

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#462]
Currently you have to

```
cd /var/docker
./launcher start app
```
every time.

It should use [Docker restart policies](http://docs.docker.com/reference/commandline/cli/#restart-policies). We have to recreate the container to do that.

**Comment by mlandauer** [comment]
I think this might be fixed now

**Comment by mlandauer** [comment]
I checked by doing "docker inspect" on the server and the discourse container has its restart policy to always restart. So, pretty sure this is fixed now.
