### ISSUE TITLE
morph.io security certificate expired

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#466]
>The certificate expired on 21/01/15 04:20

**Comment by mlandauer** [comment]
Fixed.

**Comment by henare** [comment]
Legend.

Maybe we should put these expiry dates on the calendar?

**Comment by mlandauer** [comment]
I think that's a good idea. Is there a service that can look up the certs and remind you automatically of expiry?

**Comment by henare** [comment]
And also domains!

How about writing a morph.io scraper that collects all of these automatically and then hook up Hubot to query the morph.io API and remind the Slack room when expiries are coming up ;)

**Comment by mlandauer** [comment]
You crazy man
