### ISSUE TITLE
Buildpack scraper run never completes

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#468]
See this one by @ahx https://morph.io/ahx/city_council_leipzig_recent_papers

**Comment by mlandauer** [comment]
@ahx I recently upgraded the buildpack infrastructure which solved a long-standing file permissions mismatch between the buildpack and non-buildpack infrastructure which might have been causing the problem you were seeing.

Would you be willing to give buildpacks another go? If so, let me know and I'll enable it again for you.

**Comment by ahx** [comment]
Hi!

sounds good. Please enable buildpacks for me and I will add a new version of the scraper. 

Cheers,

Andreas

**Comment by mlandauer** [comment]
Great! @ahx I've enabled buildpacks for you again. If you run into any trouble don't hesitate to add an issue. Similarly if things work fine it would be great to know. Comment on this issue if it makes sense.

**Comment by ahx** [comment]
Now it just works. Thanks!

**Comment by mlandauer** [comment]
Closing this as fixed
