### ISSUE TITLE
Easy scraper discovery

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#47]
One of the dreams of ScraperWiki was that if a scraper already existed for the data you wanted, you wouldn't have to rewrite it.

That never really materialised as I'd often get half way through writing a scraper only to find someone else had kinda already done it.

I'd like a central place to really quickly check if someone has scraped something similar. It needn't be complex. Maybe just a quick search of URLs that scrapers using this platform have hit? (#32)

**Comment by mlandauer** [comment]
Since search now covers scraped urls I think we can close this
