### ISSUE TITLE
Renew faye.morph.io certificate

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#470]
It expires 08/03/15.

**Comment by mlandauer** [comment]
I'm picking that up. I'm going to look at renewing the morph.io certificate at the same time so in future they expire at the same time.

**Comment by mlandauer** [comment]
Fixed by 6eced410b714ba2467d81af2c6d9d3f59a9df849

**Comment by henare** [comment]
:frog: thanks Matthew!

**Comment by petrbouchal** [comment]
This seems to coincide with the certificate becoming invalid for api.morph.io.
