### ISSUE TITLE
Make the console view resizable

### ISSUE THREAD

**Issue by joonjoonjoon** [openaustralia/morph#478]
super easy fix, but will be great for people who do a lot of console writing.
(like me: https://morph.io/joonjoonjoon/cellphones-directory)

**Comment by mlandauer** [comment]
It would be fantastic if you could supply a pull request for this or an explanation of precisely how the CSS should be changed!

**Comment by joonjoonjoon** [comment]
good point :) 

the css would be

resize: both;
overflow: auto;

**Comment by joonjoonjoon** [comment]
I made a pull request.
It was kind of a hassle just to suggest 2 lines of CSS, but I guess that's the proper way  :)
