### ISSUE TITLE
PHP error -  with simple_html_dom.php and mb_detect_encoding() function

### ISSUE THREAD

**Issue by hailspuds** [openaustralia/morph#486]
Hey,

Regarding this scraper:

https://github.com/planningalerts-scrapers/sorell

It has been throwing an error:

PHP Fatal error: Call to undefined function mb_detect_encoding() in /app/vendor/openaustralia/scraperwiki/simple_html_dom.php on line 1234

I'm not sure, but I don't think that's the scraper erroring. It seems to be a problem with the simple_html_dom class?

**Comment by mlandauer** [comment]
@hailspuds thanks for letting us know! I think this is likely something that I've broken recently when upgrading the whole buildstep infrastructure. I'll have a chance to look a little later today.

**Comment by mlandauer** [comment]
First step. I've been able to reproduce the problem on my local dev copy of morph

**Comment by mlandauer** [comment]
Deploying the fix to production now and I'll re-run the scraper manually to double-check that it's all okay.

**Comment by mlandauer** [comment]
Cool. That's all fixed now. See https://morph.io/planningalerts-scrapers/sorell

Thanks again @hailspuds for your help!
