### ISSUE TITLE
Make buildpacks the default

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#491]
There are a few outstanding issues relating to buildpacks. Once these are resolved it would be good to move everyone over to using buildpacks.

**Comment by ahx** [comment]
:+1: For a scraper using Ruby, buildpacks worked really well.

**Comment by mlandauer** [comment]
The plan is
* make buildpacks the default for new users/orgs.
* Create a rake task to switch over everyone to buildpacks.
* Remove the notice on the scraper page about buildpacks. 
* Update the documentation

Leave the ability to switch buildpacks off for individual users/orgs if it ends up causing any problem

Then, once it's stable and being used and everybody is happy we can remove the non-buildpack support from the code base which will make me very happy.
