### ISSUE TITLE
Vagrant provision fails with unknown ssh error

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#495]
When Vagrant runs the Ansible provisioning step it fails with:

    fatal: [local] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

Running the generated `ansible-playbook` command using -vvvv SSH debugging gets us this:

```
[snip]
debug1: Trying private key: /home/henare/Documents/projects/openaustralia/code/morph/.vagrant/machines/local/virtualbox/private_key
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
debug3: sign_and_send_pubkey: RSA 3d:b1:f0:3d:ed:b2:a8:1f:c3:42:eb:9b:e7:8e:ca:5f
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey,password).
```

**Comment by mlandauer** [comment]
@henare it's really icky right now. When running under vagrant you need to comment out a line (``user:root``) in the playbook.yml

**Comment by henare** [comment]
@mlandauer thanks for that. I would've been chasing my tail all day otherwise.

**Comment by mlandauer** [comment]
No worries. I did a fair amount of chasing my tail last week when I was getting started with this. :-)
