### ISSUE TITLE
Owner tooltip on new scraper page contains HTML

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#496]
Hover over the owner drop-down on the new scraper page to reproduce:

![selection_002](https://cloud.githubusercontent.com/assets/48945/6818571/4ead3942-d306-11e4-9b3a-f9fb47e1bbb5.png)

**Comment by mlandauer** [comment]
I can't reproduce the error. I don't see any html in the tooltip, just the nickname. I tried on both Chrome and Firefox. Maybe it's been fixed by the recent updates to gems?

@henare could you confirm that it's fixed and close if it is. Thanks!

**Comment by henare** [comment]
It's fixed!
