### ISSUE TITLE
Stay signed in

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#497]
It seems that every time I visit morph.io I have to sign it. I'd like to stay signed in please.

**Comment by mlandauer** [comment]
I wonder if this is because deploys are trashing session data? Hmmm... Will investigate

**Comment by mlandauer** [comment]
Session info is just stored client side. @henare are you closing browsers between morph.io sessions by any chance?

**Comment by mlandauer** [comment]
@henare I've deployed the fix and tested it using firefox. I'm reopening the issue so you can check it works for you. Once you've tested and it works please close the ticket.

By the way I wasn't seeing this issue because I've been using chrome.

**Comment by mlandauer** [comment]
I'm going to assume this is now fixed
