### ISSUE TITLE
No documentation of how to use secret environment variables

### ISSUE THREAD

**Issue by philipnye** [openaustralia/morph#503]
Secret environment variables are a great feature, but as far as I can see there's nowhere in the documentation that explains how to use them.

I was able to figure it out after a while, following what @maxious has done in his cat photos scraper (https://github.com/maxious/cat_photos, via #202). But in the next update of the documentation it'd probably be worth adding a section on using secret variables.

(In the interim, for Python scrapers at least, the approach seems to be as follows
`import os          #needed in order to access the secret variable(s)`
`if 'MORPH_MYSECRET' in os.environ:      #make code conditional on existence of a secret variable`
`os.environ['MORPH_MYSECRET']        #use the secret variable`

where MYSECRET is the suffix you've chosen for your secret variable.)

**Comment by henare** [comment]
@lucahammer wants this https://twitter.com/luca/status/593280920699928576

**Comment by mlandauer** [comment]
It would be really helpful if there was a link to the documentation as well from the place on the settings page where you can set the variables

**Comment by jhroy** [comment]
For Ruby users out there, I used the ENV class, then passed each of my four Secret Environment Variables to a new local variable:

```
cle1 = ENV['MORPH_1']
cle2 = ENV['MORPH_2']
cle3 = ENV['MORPH_3']
cle4 = ENV['MORPH_4']

client = Twitter::REST::Client.new do |config|
  config.consumer_key = cle1
  config.consumer_secret = cle2
  config.access_token = cle3
  config.access_token_secret = cle4
end
```

**Comment by mlandauer** [comment]
As this came up again yesterday. It's high time to fix this!

**Comment by mlandauer** [comment]
It would be good to add hints that this documentation exists in a few places. The most obvious place that I can think of is to add a link in the template code when you create a new scraper. That's a place where you're using code that's in public and so you might be faced with the problem of "how do I include my secret keys here?" so it should be the place that we remind people that they *can* use secret values.
