### ISSUE TITLE
ArgumentError - invalid date

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#504]
## Backtrace

    line 58 of [PROJECT_ROOT]/lib/morph/database.rb: sql_query
    line 194 of [PROJECT_ROOT]/app/controllers/scrapers_controller.rb: block (3 levels) in data
    line 193 of [PROJECT_ROOT]/app/controllers/scrapers_controller.rb: block (2 levels) in data

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/35868/faults/11888248)

**Comment by henare** [comment]
The link in the error works for me now.
