### ISSUE TITLE
Add search over urls scraped

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#509]
Giving you then the scrapers that scrape that domain. Related to #103

**Comment by mlandauer** [comment]
It would make sense that we return the scrapers that scrape the particular domain that's being search for. In that case, and probably more generally, we should show the url of the domain in the scraper list. That's actually really useful information about a scraper.

**Comment by mlandauer** [comment]
There's no doubt not enough space to show the meta information for the domain as well. So, it would be good to show that at least in a tooltip when you hover over the domain. If you want more information and the tooltip isn't available (on touch devices for instances) then you can always click on the scraper to see that information

**Comment by mlandauer** [comment]
Should we split the display of the url on the scraper lists out as a separate ticket?

**Comment by equivalentideas** [comment]
> Should we split the display of the url on the scraper lists out as a separate ticket?

I think so, I can do that.

**Comment by mlandauer** [comment]
Let's ignore the meta information for the time being

**Comment by mlandauer** [comment]
First pass of this is done
