### ISSUE TITLE
Error when editing/adding a secret environment variable

### ISSUE THREAD

**Issue by philipnye** [openaustralia/morph#510]
I'm currently getting this error when I press the 'update' button to save an edited, or a new, secret environment variable in the settings page:
![error](https://cloud.githubusercontent.com/assets/5579544/6897612/aea062e0-d6ec-11e4-9fba-2647be2cc451.png)

I'm getting the following in the console upon pressing 'update':
`2015-03-30 15:00:03.625 POST https://morph.io/philipnye/free-school-ofsted-ratings-output-test 404 (Not Found) /philipnye/free-school-ofsted-ratings-output-test:1`

`2015-03-30 15:00:03.811 Navigated to https://morph.io/philipnye/free-school-ofsted-ratings-output-test`

The page https://morph.io/philipnye/free-school-ofsted-ratings-output-test does exist though, and I'm pretty sure saving was working properly yesterday.

Thanks

**Comment by philipnye** [comment]
I should perhaps add, the scraper itself is working fine (including calling secret environment variables).

**Comment by mlandauer** [comment]
@philipnye thanks for the excellent bug report. That's fixed now and rolled out to production. If you see anything else not working don't hesitate to let us know.

**Comment by philipnye** [comment]
Great, thanks for dealing with so quickly @mlandauer!
