### ISSUE TITLE
NoMethodError: undefined method `new_session_path' for #<Users::OmniauthCallbacksController:0x...>

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#511]
See https://app.honeybadger.io/projects/35868/faults/4813964#notice-summary

I think this happens when someone doesn't accept the github login stuff. It would be good to fix this as it's a bad user experience (we can for instance link to an explanation of why we are asking for the particular github permissions) and it causes several exceptions per week otherwise

**Comment by henare** [comment]
Duplicate of #347.
