### ISSUE TITLE
Elasticsearch not starting automatically at boot

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#517]
For some reason

**Comment by mlandauer** [comment]
@henare can you offer any insight on this as you installed on elasticsearch on kedumba?

**Comment by henare** [comment]
@mlandauer it's actually installed on `jamison` because `kedumba` is too old! I didn't do anything special to get it to start, I just installed the package.

AFAIK it also Just Works on the Ansible setup.

**Comment by mlandauer** [comment]
Ah okay. Thanks. That's what I thought. Just needed to check. So, the fact that it's not starting is weird.. Hmmm...

**Comment by henare** [comment]
`/etc/init.d/elasticsearch` seems to be configured fine:

```
### BEGIN INIT INFO
# Provides:          elasticsearch
# Required-Start:    $network $remote_fs $named
# Required-Stop:     $network $remote_fs $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch
# Description:       Starts elasticsearch using start-stop-daemon
### END INIT INFO
```

**Comment by henare** [comment]
I can reproduce this on my local Vagrant machine.

**Comment by henare** [comment]
The Ansible role we're using [only supports](https://github.com/f500/ansible-elasticsearch/blob/master/meta/main.yml#L10-L13) Debian Wheezy.

There are plenty more higher rated roles on Galaxy, including the one we use on the TVFY Ansible build. I'll look at switching to one of those.

**Comment by mlandauer** [comment]
@henare ah awesome. I didn't spot that. Switching to one that works would be great!

**Comment by henare** [comment]
Arrg, well after a fun journey trying to use the same Ansible role as we'll use on TVFY I've resorted to Do The Dumb thing.

**Comment by mlandauer** [comment]
Much appreciated!
