### ISSUE TITLE
Long running jobs not stopping

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#520]
This morning I woke up to discover the following jobs stuck in the queue:
* Up 3 hours - DoomyTheFroomy_agenturen_fuer_arbeit
* Up 4 hours - DoomyTheFroomy_berlin_school_atlas
* Up 6 hours - soit-sk_scraper-sk_company_register
* Up 8 hours - catarak_pitchfork_review_data
* Up 10 hours - benfb_pitchfork_review_data

They were still running and so were taking up all the slots in the queue which was stopping about 50 other scrapers from running.

What I expect to happen is for a scraper to be killed automatically if it runs over 4 hours.

**Comment by tn2226** [comment]
I am also experiencing long queues, with no console reports. I'm a noob at Morph.io, so take this comment for what it is. Is this normal to have long waits?

**Comment by mlandauer** [comment]
@tn2226 we've been doing some big upgrades to morph.io recently and we're experiencing some teething stability and queue issues. It's not normal but has been happening on and off a bit over the last few days. We're working to stabilise everything as quickly as possible.

**Comment by mlandauer** [comment]
@tn2226 the queue is working through a backlog now. Hopefully it should be cleared within the next 5-10 minutes

**Comment by tn2226** [comment]
@mlandauer Thanks so much for you help! I finally got a scraper to work. Dancing now.

**Comment by mlandauer** [comment]
Closing this now
