### ISSUE TITLE
Update available Tweepy library

### ISSUE THREAD

**Issue by philipnye** [openaustralia/morph#528]
The version of Tweepy that is currently available in Morph (1.7.1, per [this](https://github.com/openaustralia/morph-docker-python/blob/master/pip_requirements.txt)) no longer allows tweets to be posted as far as I can tell. (I got an error in my scraper, and [the second answer here](http://stackoverflow.com/questions/22466801/using-ssl-verification-with-tweepy) seems to suggest that Twitter now requires SSL verification, which was first added to Tweepy v2.2).

I've successfully run my script using Tweepy v3.2.0, installed via [buildpacks](https://morph.io/documentation/buildpacks), so propose that a more up-to-date version of Tweepy is made available in core Morph.

Cheers :)
Philip

**Comment by mlandauer** [comment]
Since buildpacks are now the default everywhere this shouldn't be necessary anymore. So, closing this issue.
