### ISSUE TITLE
Nav search breaks out of container on small screens

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#550]
The search form in the header sits outside the consistent side container margin on small screens:

![screen shot 2015-04-09 at 5 01 14 pm](https://cloud.githubusercontent.com/assets/1239550/7061842/113c2ea8-deda-11e4-97c4-047c0109f513.png)

**Comment by mlandauer** [comment]
I'm still seeing this on the smallest screen size

**Comment by equivalentideas** [comment]
Yeah sorry I mistakenly referenced it in those commits above.
