### ISSUE TITLE
Use full name, org and country in quotes section

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#555]
They're quotes from people and we prioritise full names above handle on the morph people page so we should do the same here.

We should also include their organisation if they have one because we are appealing to civic hackers and open data folk.

We should also include their country because morph is used by people all over the world.

So, specifically instead of
```
rezzo
```

it should say
```
J. Pablo Pérez Trabucco
Fundación Ciudadano Inteligente
Chile
```

**Comment by equivalentideas** [comment]
Nice, I totally agree.

On twitter @hailspuds lists the ABC as his org/employer, I wonder he minds if we list that on the site?

> Will Ockenden
> Radio Journalist, ABC
> Australia

**Comment by mlandauer** [comment]
@equivalentideas I think we should just go ahead and list him like that. We're not implying that it's somehow "officially sanctioned" by the ABC. If it's a problem, he can get in touch and let us know and we'll remove it.

**Comment by mlandauer** [comment]
@equivalentideas Also in Will's case I would list the ABC with its full name rather than the acronym because most people using morph are not from Australia so don't know what the ABC is.

**Comment by equivalentideas** [comment]
Sounds good :+1:

**Comment by equivalentideas** [comment]
closed by https://github.com/openaustralia/morph/commit/c5df1a8fc10bbed672ebf1a1a1f880756741dac6
