### ISSUE TITLE
Remove the big logo from the longer text introduction section

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#556]
The big, cartoony logo doesn't match the more photographic, polished character of the new home page.

We could remove it and expand the text to fill the whole space.

Maybe we should add another call to action at the bottom of the text? relates to #420 .

![screen shot 2015-04-10 at 10 56 00 am](https://cloud.githubusercontent.com/assets/1239550/7080133/9bf73eac-df70-11e4-93a4-0566edc536fc.png)

**Comment by mlandauer** [comment]
:+1:
