### ISSUE TITLE
Put "number of records of data" next to "number of scrapers" on landing page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#577]

**Comment by mlandauer** [comment]
I think I'll add list of scrapers to the admin interface with the number of rows of data that each scraper has. Then, we can hopefully download a CSV of all the scrapers and get the info that way.

Hopefully make something that's valuable in other ways while getting the information we need.

**Comment by equivalentideas** [comment]
> Hopefully make something that's valuable in other ways while getting the information we need.

Sounds great :+1:

**Comment by mlandauer** [comment]
Done and deploying now
