### ISSUE TITLE
make table fade out scroll affordance adapt to citizen interaction

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#588]
The fade out on the side of a data table is a little tip to the user that there is more of the table off to the right.

![screen shot 2015-04-15 at 3 29 48 pm](https://cloud.githubusercontent.com/assets/1239550/7152713/4c92e1b4-e384-11e4-9204-2ab02900a055.png)

But, when they scroll over and there isn't any more to see, it is still there:

![screen shot 2015-04-15 at 3 25 44 pm](https://cloud.githubusercontent.com/assets/1239550/7152717/5eb4001c-e384-11e4-813e-7069343af368.png)

The fade should be on whichever side has more table to reveal, or both.

**Comment by mlandauer** [comment]
:+1:

**Comment by equivalentideas** [comment]
fixed by https://github.com/openaustralia/morph/commit/b6c322228f485c73b397dc1503040578679524f0
