### ISSUE TITLE
Is table size table specific or for the whole database?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#591]
Above a scraper's data table (see [this one](https://morph.io/soit-sk/slovakia_post_codes) for example) it says:

> rows 10 / 3948 (697 KB)

Then I swap tables via the tab interface under the 'Data' heading, and it now says:

> rows 10 / 5019 (697 KB)

Which makes me think "How can these tables be the same size if one has 1000 less rows?"

I assume it's the same because that's the figure for the whole database. If that's the case, maybe the size should be with the database download link and the table's size should be with the csv table download—if that's necessary.

**Comment by mlandauer** [comment]
Yup that's definitely wrong. The size in kb is for the whole database and not just for the table so the way it's currently shown on databases with more than one table is completely confusing.

**Comment by equivalentideas** [comment]
What do you think about moving it to the download link, so it's clearly connected the database size, as a first iteration:

![screen shot 2015-04-15 at 5 07 15 pm](https://cloud.githubusercontent.com/assets/1239550/7153679/f31a65f4-e391-11e4-84e2-9235db243ae3.png)

**Comment by mlandauer** [comment]
Sounds good to me!

**Comment by equivalentideas** [comment]
Cool, I’m on it.
