### ISSUE TITLE
Bottom of title text cut off on scraper page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#594]
For example see https://morph.io/pganda/diputados_morphio

![morph pganda diputados_morphio](https://cloud.githubusercontent.com/assets/2221/7169926/611b5a42-e40d-11e4-88a5-0bb0f2b84639.png)

**Comment by mlandauer** [comment]
The problem is still there in production. Your fix @equivalentideas was deployed to production, right?

**Comment by equivalentideas** [comment]
It is, but silly me messed it up! I'll revert it and fix the value and resubmit.

**Comment by mlandauer** [comment]
Thanks!

**Comment by equivalentideas** [comment]
This is now fixed by https://github.com/openaustralia/morph/commit/92e120b1f3eb8408032d2b845ca9d8c9e65f0f0d
