### ISSUE TITLE
make table header more distinct using bootstrap table header style

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#596]
By default, bootstrap will display a `<thead>` with a style to make it stand out from the body rows. An easy win on table readability for morph users I think, and it also makes our table markup more semantic and accessible.

## With <thead>
![screen shot 2015-04-16 at 11 20 41 am](https://cloud.githubusercontent.com/assets/1239550/7172412/ff1b7426-e42a-11e4-9f56-4aa31c167ad5.png)

## Current
![screen shot 2015-04-16 at 11 20 26 am](https://cloud.githubusercontent.com/assets/1239550/7172415/0757be10-e42b-11e4-9f66-b8014e537ad5.png)

**Comment by mlandauer** [comment]
:+1:
