### ISSUE TITLE
Change "Morph" to "morph.io"

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#604]
Use the same name everywhere including

* Title of pages
* Email alerts

**Comment by equivalentideas** [comment]
Should this be changed form the github application name instructions? https://github.com/openaustralia/morph/blob/master/README.md#to-install

I'm not sure if that will mess anything up.

**Comment by mlandauer** [comment]
I totally forgot we had that configuration setting. I wonder if it's still the right way to go? Hmm... not clear to me.

If it is the right way to go then we should ensure that it's used everywhere it should be and then we just change the configuration in production.

Or, if we get rid of that setting we just remove it and hardcoded the value to "morph.io"

**Comment by equivalentideas** [comment]
I'm pretty far through hardcoding the change—but the config setting feels like the right way to go to me because looking at all the places it appears, it could be easy to get confused between where it's written as the title and where it's written as the domain. Does that make sense?

**Comment by mlandauer** [comment]
I'm not clear by what you mean by "where it's written as the title and where it's written as the domain". Morph started by being the name of scraper platform and it had a domain of morph.io and then when we launched we found everyone was referring to it as morph.io. So, it makes sense to just consistently refer to it as morph.io everywhere.

**Comment by equivalentideas** [comment]
@mlandauer I think we might be talking about different things.

> I totally forgot we had that configuration setting.

Are you talking about a config setting for the site title that can be referenced where ever we need to display the site title in text throughout the app?

> I'm not clear by what you mean by "where it's written as the title and where it's written as the domain". 

I mean in places in the code where the domain is written and where the site title is written near each other, it could be clearer for developers to use a variable for the site title so that there's no potential confusion. But it doesn't happen very often, probably not a big worry.

**Comment by mlandauer** [comment]
> Are you talking about a config setting for the site title that can be referenced where ever we need to display the site title in text throughout the app?

Yes :-)

> I mean in places in the code where the domain is written and where the site title is written near each other, it could be clearer for developers to use a variable for the site title so that there's no potential confusion. But it doesn't happen very often, probably not a big worry.

I think I understand now. Can you point me at a specific example in the code just to be sure?

**Comment by equivalentideas** [comment]
> I think I understand now. Can you point me at a specific example in the code just to be sure?

Here's one https://github.com/openaustralia/morph/blob/master/spec/models/domain_spec.rb#L14

I'm pretty much done the hardcoding.

**Comment by equivalentideas** [comment]
Should references to the command line tool be changed too?

> [openaustralia/morph-cli](https://github.com/openaustralia/morph-cli) - Command-line morph tool

Becomes

> [openaustralia/morph-cli](https://github.com/openaustralia/morph-cli) - Command-line morph.io tool

**Comment by mlandauer** [comment]
@equivalentideas that's in the README right? Yeah I think that should change too

**Comment by equivalentideas** [comment]
> that's in the README right?

Yep.

**Comment by equivalentideas** [comment]
Should we also change the git repo name?
