### ISSUE TITLE
HTML shouldn’t render in data table

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#608]
In the scraper data table, if the scraper collects HtML, it should render as plaintext so that citizens can see the raw material collected. If it renders as formatted HTML, there could be content that isn't visible, in html attributes etc.

The rendering of block elements in the table, such as `<h2>` or `<p>`, also messes up the formatting of the table.

See https://morph.io/equivalentideas/santos_news_announcements

**Comment by equivalentideas** [comment]
same bug is causing images to render see https://morph.io/haighd2/rightmove_scraper_1

**Comment by equivalentideas** [comment]
I've marked this as a security issue as it seems to me you could inject scripts into the page.

**Comment by mlandauer** [comment]
I'm fairly certain there isn't a security issue. It uses `auto_link` which returns sanitized html so you couldn't inject something nasty.

**Comment by equivalentideas** [comment]
> I'm fairly certain there isn't a security issue. It uses auto_link which returns sanitized html so you couldn't inject something nasty.

Nice, I labeled it just in case. I'll remove that.

**Comment by henare** [comment]
I think it's convenient for URLs to still be links so we should leave that in.

**Comment by henare** [comment]
My first idea was to just escape the HTML and run it through auto_link but that does things like this:

![selection_001](https://cloud.githubusercontent.com/assets/48945/7292269/b63f3982-e9dd-11e4-9829-437419b09a48.png)

Which we definitely don't want. This scraper is another example of why we don't want to render HTML: https://morph.io/frabcus/list_of_r_user_groups#data-table

However the links really are useful so I think our rule needs to be if the cell contains one URL or one email address then we automatically create a link and in all other cases we display the raw string.
