### ISSUE TITLE
Scraper page can be huge

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#612]
When _some people_ \*cough* @equivalentideas \*cough* write scrapers with crazy amounts of output the page can be rather large, e.g. 7.8MB! https://morph.io/equivalentideas/santos_news_announcements

**Comment by mlandauer** [comment]
We're now automatically limiting log output to a maximum of 10,000 lines. See #1039. So, this shouldn't happen anymore on new runs

**Comment by henare** [comment]
I've just checked a couple of scraper pages that used to be massive and they're now a quite respectable ~1.5MB or so. Really nice work @mlandauer :fire:
