### ISSUE TITLE
Selecting a different item in dropdown menus doesn't work

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#621]
I'm using Firefox. To reproduce:

* _Add Scraper_ => _New scraper_
* Try to select a different language

The menu appears but when you select a different language it doesn't actually change. The same happens with the other drop down menus.

**Comment by mlandauer** [comment]
Well that's awful!

**Comment by mlandauer** [comment]
I can't reproduce this on Firefox 36.0.4 on Mac OS X

**Comment by mlandauer** [comment]
Nor can I reproduce this on Firefox 37.0.1 on Mac OS X 10.10.3

**Comment by henare** [comment]
Hmm, maybe it's one of my add-ons blocking something. I'll have a play around.

**Comment by henare** [comment]
Wack. I didn't notice that Firebug was active on Morph.io - disabling it made this problem go away.

Closing this as "Henare's browser sucks".
