### ISSUE TITLE
Data table has empty scroll bars

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#622]
https://morph.io/openaustralia/nsw_agencies_from_directorynswgovau

![selection_001](https://cloud.githubusercontent.com/assets/48945/7244146/67d76ad6-e81a-11e4-9376-d528b76d2d90.png)

**Comment by mlandauer** [comment]
@henare that links isn't working for me

**Comment by henare** [comment]
@mlandauer refresh - I updated it after I got around #621

**Comment by mlandauer** [comment]
@henare - what do you mean by "empty scrollbars"? That table is small enough that it shouldn't need scrolling. Is that what you mean?

**Comment by henare** [comment]
I don't think these things supposed to be there:

![67d76ad6-e81a-11e4-9376-d528b76d2d90](https://cloud.githubusercontent.com/assets/48945/7244698/c4bf923e-e822-11e4-80d2-33d8ba92cdc6.png)

**Comment by mlandauer** [comment]
Ah! Gotcha. I'm not seeing those on Chrome on OS X nor on Firefox on OS X. Is this a Linux only thing or is something else?

**Comment by henare** [comment]
>I'm not seeing those on Chrome on OS X nor on Firefox on OS X. Is this a Linux only thing or is it something else?

Weird! I also see them in Chrome. Must be a Linux only thing?

![selection_001](https://cloud.githubusercontent.com/assets/48945/7244769/c7ea2bc6-e823-11e4-970e-7a50b2ca4369.png)

**Comment by equivalentideas** [comment]
@henare can you try something in the styles inspector? Try changing: 

```
.tablesaw-enhanced .table-responsive.scraper-data {
   overflow: scroll;
}
```

to overflow: auto;

Does that remove the scroll bars?

**Comment by henare** [comment]
>Does that remove the scroll bars?

@equivalentideas :+1:
