### ISSUE TITLE
Data table headings overlap content on small screens

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#623]
https://morph.io/hailspuds/foi-disclog-dfat

![selection_001](https://cloud.githubusercontent.com/assets/48945/7244169/e50531a0-e81a-11e4-96f1-49edc46aa87f.png)

**Comment by equivalentideas** [comment]
This is because it isn't picking the `word-break` in:

```
.tablesaw-enhanced .table-responsive.scraper-data .tablesaw>tbody>tr>td {
  white-space: normal;
  word-break: break-word;
}
```

for some reason. Investigating now.

**Comment by equivalentideas** [comment]
It's because `break-word` isn't a valid attribute of `word-break` https://developer.mozilla.org/en-US/docs/Web/CSS/word-break .

I'll change this to `word-break: break-all`!

**Comment by henare** [comment]
Then break dance :dancers:
