### ISSUE TITLE
The display of user search results is messy and should do more to emphasise the human.

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#633]
Here's the current display of user search results:

![screen shot 2015-04-21 at 1 25 24 pm](https://cloud.githubusercontent.com/assets/1239550/7267286/baa23264-e8fb-11e4-907b-f041ab44b309.png)

Here's the discussion of this on #507:

> In the results for people I think we prioritise identifying information, rather than information about their morph activity. So for people: full name, image, user name, organisations, above number of scrapers, amount of data collected. For organisations: full name, image, user name, number of members (maybe member images?), above number of scrapers etc.

**Comment by equivalentideas** [comment]
I think the simple first step here is to adjust the hierarchy/sizes of the personal information and remove the scraper count. I think there is room for doing something interesting with activity information, to reward and highlight people doing great work, but i think that is for a further iteration.

I think the first pass is to:

* turn to the full name into the object heading (use the nickname if there's no full name)
* make the image a bit bigger
* move the image and information closer together
* remove to activity information (number of scrapers and contributions).

Here's a rough sketch:

![2015-04-22 16 07 18](https://cloud.githubusercontent.com/assets/1239550/7268294/4d0786a4-e90b-11e4-84e3-a675962cdf6c.jpg)

(note that the username shouldn't actually have an @ before it)

I think we could also do something interesting with a grid layout rather than a list, like [Twitter user search](https://twitter.com/search?q=civictech&src=typd&vertical=default&f=users) or the [github contribs page](https://github.com/openaustralia/morph/graphs/contributors).

**Comment by mlandauer** [comment]
:+1:

**Comment by mlandauer** [comment]
Reopened. See #640
