### ISSUE TITLE
If search returns no results at all (for scrapers or users) message is at wrong place in the hierarchy

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#636]
See for example: https://morph.io/search?q=dsjfhsdkjfhkjsd

![morph io](https://cloud.githubusercontent.com/assets/2221/7268883/3104f102-e911-11e4-99c9-47e1fec6f14f.png)

The message refers to both users and scrapers yet is within the tab for both users and scrapers. This is a bit strange.

In this case it would be better if the tabs were not there at all because the message refers to both scrapers and users.

**Comment by equivalentideas** [comment]
When @mlandauer and I spoke about this last week we saw 2 steps to this:

1. [ ] remove the tabs if there are no results of any type.
2. [ ] do something more pronounced if there are no results for a type, but there are for the other. Make sure citizens know there are results of the other type.

Here's that current text, pretty minimal:

![screen shot 2015-04-28 at 11 14 07 am](https://cloud.githubusercontent.com/assets/1239550/7361197/df9cdf06-ed97-11e4-9fe2-0a5e2c4caa66.png)

**Comment by equivalentideas** [comment]
closed by merging https://github.com/openaustralia/morph/pull/654
