### ISSUE TITLE
Search is being done on data that isn't always shown

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#637]
This is confusing and could potentially leak information.

See for example https://morph.io/search?utf8=%E2%9C%93&type=users&q=ios

![morph io](https://cloud.githubusercontent.com/assets/2221/7268982/46fe4c46-e912-11e4-895e-6f250fa424c4.png)

The first two results are matching on something that isn't shown.

It should just be a matter of fixing the fields that searchkick (elasticsearch) is indexing

**Comment by henare** [comment]
Fixed in #641.
