### ISSUE TITLE
frequent hangs of soit-sk/scraper-sk_company_register

### ISSUE THREAD

**Issue by hanecak** [openaustralia/morph#660]
soit-sk/scraper-sk_company_register is configured to run daily. But it frequently "hangs" with following:

```morph.io internal error: Sidekiq::Shutdown
Stopping current container and requeueing```

Manual stop is needed before scrapper gets re-run again. Thus, if I do not check frequently, scraper is stuck for a long time doing nothing.

When I run scraper from command line, no hangs occur.

**Comment by henare** [comment]
I've seen this on other scrapers too. The big problem is that it says it's being requeued but from what I can tell it never is.

**Comment by hanecak** [comment]
While scheduling still has some gaps (there are not 30 runs reported for past month), scraper is now run quite regularly.

And for past few weeks, even months, this particular bug was not encountered.

So I'm closing this one.
