### ISSUE TITLE
ScraperWiki locally names db table "swdata", morph names table "data"

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#661]
By default, morph.io names my sqlite database table 'data', ScraperWiki names it 'swdata' locally using the default value for [save_sqlite()](http://www.rubydoc.info/gems/scraperwiki/ScraperWiki#save_sqlite-instance_method). This is when I run my scraper with `ruby scraper.rb`.

Just noting that I found this confusing as a user. I'll investigate further myself. I think it could be todo with ruby versions. I'm running 2.1.1, morph [docs says I have access to 1.9.2-p320](https://morph.io/documentation#libraries).

**Comment by mlandauer** [comment]
This is because you have the default scraperwiki gem installed.

For morph there is a different version which you install by creating a Gemfile with
```
gem 'scraperwiki', git: "https://github.com/openaustralia/scraperwiki-ruby.git", branch: "morph_defaults"
```

then `bundle install` as per usual

and run your scraper with
```
bundle exec ruby scraper.rb
```

**Comment by equivalentideas** [comment]
Thanks for that @mlandauer . Why doesn't morph.io include a Gemfile when it gives you the template ruby scraper repo?

**Comment by mlandauer** [comment]
It does if buildpacks are enabled

**Comment by equivalentideas** [comment]
ah nice, so won't be an issue much longer :+1:
