### ISSUE TITLE
meta info for each scraper page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#663]
Make the meta info for a scraper page be a simple summary of that scraper and possibly the domains that it scrapes. This would be much better than what it currently does which is just the default site-wide meta info about morph.io

**Comment by equivalentideas** [comment]
In summarising scrapers, using the description could be good, as many of them include keywords that someone might be searching for.

I think the scraper descriptions would be a good first cut. With a fallback for no description like:

> A scraper to collect structured data from the web.

Then I think the next thing we could do is add stuff about the domains if there's no description:

> A scraper to collect data form example.com, example2.com, example3.com and 4 other domains.

Other thoughts:

Data is also a keyword here, maybe there's a way we can insert that somewhere when there is a description?

This is interesting, structured data in descriptions https://support.google.com/webmasters/answer/35624?rd=1#1 .

Also it may be worth no truncating a long list of domains in this case. This post has [some tests](http://www.searchenginepeople.com/blog/meta-description-length-google-2011.html#ixzz3aSS2qbHU) on description length:

> If you use sentence breaks, you can have your snippet show for a keyword search if that keyword appears before the 265th character in your description.

> You can potentially have up to the 380th character in your description show in the snippet if the keyword searched for appears before the 265th character (my guess is that it would go up to character 410 or so - if your keyword starts a sentence and its last letter is just before that 265th character).

**Comment by mlandauer** [comment]
All these are good suggestions. Part of me thinks that including some mention of morph.io in the meta description would be good. Part of me thinks it would be a distraction (and it's included in the url anyway).

**Comment by equivalentideas** [comment]
> Part of me thinks that including some mention of morph.io in the meta description would be good. Part of me thinks it would be a distraction (and it's included in the url anyway).

It is in the title tag as well. Here's a current result in google:

![screen shot 2015-05-18 at 3 17 12 pm](https://cloud.githubusercontent.com/assets/1239550/7674690/119047b2-fd71-11e4-95a0-e764b2fb37db.png)

**Comment by equivalentideas** [comment]
We could implement this with the [meta-tags gem](https://github.com/kpumuk/meta-tags), but if we didn't add a fallback many pages wouldn't have descriptions. That said, google doesn't seem to be using the description in results (probably as it's deemed it not useful), so i'm not sure if that's a regression.

If we did want to use that gem and have a fallback I think we could do it in the application controller.

**Comment by equivalentideas** [comment]
I think using the meta-tags gem, like on public whip, is the simplest way to go, I'm gonna move forward with implementing that. So first pass description will be scraper.description or simple default "A scraper to collect structured data from the web".

**Comment by mlandauer** [comment]
When you say default, you mean the fallback in case the scraper has no description, right?

**Comment by equivalentideas** [comment]
yep

**Comment by equivalentideas** [comment]
I've had a pass at the first iteration, adding the scraper.description or a fallback generic description, in #736 .

I'm now having a go at adding a `scraper_description()` helper to include the scraped domains if there are any.

**Comment by equivalentideas** [comment]
Using the [simplified_scraped_domains_list](https://github.com/openaustralia/morph/blob/master/app/helpers/runs_helper.rb#L37) helper to list the domains, but it doesn't have 'other domains' on the end, as it's the simplified version.

We want the domains list for part of a proper sentence like the [scraped_domains_list](https://github.com/openaustralia/morph/blob/master/app/helpers/runs_helper.rb#L31) helper, but without links. I'm going to add a new helper for that.

**Comment by equivalentideas** [comment]
@matthew I’m just trying to test out the description with the scraper domains in it, but it's quite had to test in the site as I don't have any domains. Is there a simple way to add domains to scrapers for development though the rails console (I can't work it out)? or maybe I should grab a little bit of production data or something?

**Comment by mlandauer** [comment]
@equivalentideas the best way to get real data is to use the "local" vagrant VM. This is basically a mirror of the setup used in production. Instructions are [here](https://github.com/openaustralia/morph#production-devops-development)

**Comment by equivalentideas** [comment]
Thanks :)
