### ISSUE TITLE
the order of 'on timer' and 'running' icons in scraper lists would be more useful swapped and is also inconsistent across the site

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#665]
In scraper lists , the order of activity icons is ![screen shot 2015-04-29 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/1239550/7385125/07583f18-ee83-11e4-8397-8d053f8a3253.png) ('on timer') then ![screen shot 2015-04-29 at 3 18 31 pm](https://cloud.githubusercontent.com/assets/1239550/7385128/1b5e1488-ee83-11e4-80a1-2143eb858cf1.png) ('running') from left to right:

![screen shot 2015-04-29 at 3 20 11 pm](https://cloud.githubusercontent.com/assets/1239550/7385140/46054922-ee83-11e4-9303-e4c12a54fe2d.png)

As the 'on timer' icon is much more common, it would be better placed closer to outside of the element, so that the less common icon 'running' is next to the whitespace to the left. This would mean that the eye can jump between scrapers based on the width of the 'info' stuff on the right. Comparing the width/length of standard elements is one the visual perception tasks the eye is best and quickest at.

It's also currently inconsistent across the site as on scraper pages it is 'running' then 'on timer':
![screen shot 2015-04-29 at 3 13 28 pm](https://cloud.githubusercontent.com/assets/1239550/7385093/6b58158e-ee82-11e4-80a6-ba88b91b2578.png)

To be clear: I think we should have the 'on timer' icon on the right of the 'running' icon.

**Comment by mlandauer** [comment]
As this is inconsistent I think this should be fixed sooner rather than later. I'll assign it to you to do real soon if that's cool.

**Comment by equivalentideas** [comment]
> . I'll assign it to you to do real soon if that's cool.

Sounds ace :+1:

**Comment by mlandauer** [comment]
A related fix which might be good to do at the same time is #664
