### ISSUE TITLE
Don't use FAQ structure for documentation

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#666]
I was reviewing the documentation and realised it could be quite easily changed from FAQ style to a readable, flowing document style.

I've got this in mind: https://gds.blog.gov.uk/2013/07/25/faqs-why-we-dont-have-them/

Is this a good idea/something we want to do?

**Comment by mlandauer** [comment]
I think it's a great idea. The documentation in its current form was pretty much thrown together. It's a quick first pass. Nothing more. Something more coherent, complete and structured would be wonderful

**Comment by henare** [comment]
Cool, I'll have a go at reworking what's there.

**Comment by mlandauer** [comment]
That would be wonderful!

**Comment by mlandauer** [comment]
#491 will involve some changes to the documentation. I was planning to do that all on a public branch. How will we coordinate this?

**Comment by henare** [comment]
How about I do a quick rework of this first, then you can add the documentation changes for #491?

**Comment by mlandauer** [comment]
Tip top!
