### ISSUE TITLE
Remove legacy non-buildpack support

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#672]
We deployed buildpacks as default on 2015-04-30. We won't want to do this for a while, until we're happy non-buildpack support isn't needed. Maybe wait a week or two?

**Comment by mlandauer** [comment]
We should check that nobody has explicitly disabled buildpack support - look for `:buildpacks: '0'` in `feature_switches`

**Comment by henare** [comment]
It's a bit of a pain to search serialized attributes so I had to this:

    Owner.all.select { |o| o.feature_switches.respond_to?(:has_key?) && o.feature_switches.has_key?(:buildpacks) && o.feature_switches[:buildpacks] == "0" }

The only owner was @soit-sk and I've just enabled buildpacks for them.

**Comment by mlandauer** [comment]
It's been 10 days or so and we've had no show-stoppers so I think I'm going to remove the legacy support

**Comment by mlandauer** [comment]
Done
