### ISSUE TITLE
Show the url of the domain being scraped in the scraper list

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#677]
This is important information about a scraper that can help people find what they're looking for. Particularly important since many scrapers don't have a clear description or title.

If we add search over scraper domains, it's important that you can see it in the search results (see #509)

Also impacts the display of scraper lists, see #674

**Comment by equivalentideas** [comment]
Here's a few potential layouts:

![screen shot 2015-05-01 at 12 16 53 pm](https://cloud.githubusercontent.com/assets/1239550/7425850/567b054c-effc-11e4-9a5b-0b872fe444bd.png)
![screen shot 2015-05-01 at 12 17 28 pm](https://cloud.githubusercontent.com/assets/1239550/7425851/567e4b9e-effc-11e4-8ce3-aadcc1284683.png)
![screen shot 2015-05-01 at 12 18 27 pm](https://cloud.githubusercontent.com/assets/1239550/7425852/5681407e-effc-11e4-8fac-147c4206543b.png)
![screen shot 2015-05-01 at 12 18 43 pm](https://cloud.githubusercontent.com/assets/1239550/7425853/56852f7c-effc-11e4-8a9f-93074143fbed.png)

The first one seems simplest.

**Comment by mlandauer** [comment]
I like the first one the best too

**Comment by equivalentideas** [comment]
I think that's a nice first pass :+1:
