### ISSUE TITLE
error message disrupts scraper list layout

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#689]
Currently in scraper lists, the 'errored' label sits on the left and indents the heading to the right.

This makes the error message more prominent that the heading itself. Many people viewing scraper lists aren't searching specifically for erroring scrapers. It is more important for them to be able to simply scan through the scrapers list, than it is to scan for erroring scrapers.

If the 'errored' label sat on the righthand side, in the place where the 'running' label sits (my understanding is these would never both be present) then it is out of the way for most uses, but is still *very* clear with it's bright red colour. Would would also still be easy to scan down the list for erroring scrapers.

I think this would make the structure of the scraper list less variable/more stable and usable.

**Comment by equivalentideas** [comment]
Here's what this could look like:

## Before
![screen shot 2015-05-03 at 5 32 25 pm](https://cloud.githubusercontent.com/assets/1239550/7444145/e386ecec-f1bb-11e4-8ce3-554e1a0bf7c9.png)

## After
![screen shot 2015-05-03 at 5 33 21 pm](https://cloud.githubusercontent.com/assets/1239550/7444147/e839690e-f1bb-11e4-99ca-4da77b620c5e.png)

**Comment by mlandauer** [comment]
:+1:
