### ISSUE TITLE
In user's list of scrapers, don't show user name

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#693]
When looking at the users list of scrapers they own, it's clear who owns the scrapers. You don't need to see it repeated in every title:

![screen shot 2015-05-04 at 9 54 38 am](https://cloud.githubusercontent.com/assets/1239550/7447569/3b50733e-f244-11e4-854e-eea9fe3033c2.png)

It would simplify and clean up these lists to remove this part of the scraper title in these lists, [as github do](https://github.com/mlandauer?tab=repositories).

We'd leave it in for 'scrapers contributed to' lists, as it's not clear who owns the scrapers in that case.

**Comment by mlandauer** [comment]
:+1:

**Comment by equivalentideas** [comment]
I'm a bit stuck on what the best way to do this is. Looked at parsing a local variable to the scraper partial "hide_owner_name" but I couldn't get that to work. Moving this back to ready.

**Comment by mlandauer** [comment]
The problem was that the `sync` helper doesn't seem to support locals. So, I did some shenanigans to extract another partial inside the sync template that we can pass whether we want to hide or show the owner
