### ISSUE TITLE
Python reinstalled when requirements updated

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#695]
On my local machine at least it seems that any change to Python libraries makes the whole language get reinstalled. This is really slow of course.

Here's what the morph.io logs look like when I run a scraper after changing the `requirements.txt`:

```
Injecting configuration and compiling...
[1G-----> Python app detected
[1G-----> Stack changed, re-installing runtime
[1G-----> Installing runtime (python-2.7.9)
[1G-----> Installing dependencies with pip
...
```

Does it really have to reinstall the whole language?

**Comment by mlandauer** [comment]
This is currently an unavoidable consequence of the way buildpacks work. So, marking this is as a "won't fix".
