### ISSUE TITLE
The logged in landing page can do more to help citizens accomplish tasks

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#698]
Currently when logged in, the [home page](https://morph.io/) doesn't do much to help citizens do the things they've come to morph.io for. It was originally put together to help the developers see what was happening in the app. It has lists of new users, active scrapers, and organisations on the site:

![screen shot 2015-05-05 at 10 54 56 am](https://cloud.githubusercontent.com/assets/1239550/7465562/89676614-f315-11e4-8077-e0f13685a010.png)

We can break down the people who visit this page into two groups:

* **Current users**: people who own and watch scrapers on morph
* **New users**: people who don't have scrapers, and likely have just signed up

Here are our current assumptions about the jobs these people want the landing page to do for them:

## Current users

*As a current user, when I log into morph.io, I want to know about scrapers that need my attention, so that I can fix them and keep getting the data I need.*

## New users

*As a new user, when I sign up, I want to discover scrapers that are interesting to me, so I can better understand why scraping is useful and something I should learn more about.*

*As a new user, when I visit the landing page, I want some help to write my first scraper on morph.io, so that I can get the data I need.*

**Comment by equivalentideas** [comment]
@mlandauer and I's initial thoughts about how we can do better for these people:

> As a new user, when I sign up, I want to discover scrapers that are interesting to me, so I can better understand why scraping is useful and something I should learn more about.

The best way we can currently help people find interesting scrapers is with search.

We could add a prominent search banner with some suggested search terms to get people started.

We should also redirect new signups to this landing page, rather than their profile as we currently do.

> As a new user, when I visit the landing page, I want some help to write my first scraper on morph.io, so that I can get the data I need.

We don't really have any documentation of how to write a scraper. We depend on people already knowing how or being skilled enough to work it out by looking at the templates/other scrapers.

We're not planning to add any new how-to's at this point, *but* we could ease people into adding a scraper, and hopefully with determination will prevail.

We had an idea that you could add a scraper from the landing page if you had none—by entering a description and title for it. We could give some direction for a good description and require it. That way, even if people can't follow through and write the scraper, they can make a repo to describe what they're after. This is a good first step for them, would be very interesting experiment, and there may be a way to then connect people who are interested to pick up those scrapers and write them.

> As a current user, when I log into morph.io, I want to know about scrapers that need my attention, so that I can fix them and keep getting the data I need.

The obvious thing to do here is show a list of scrapers that need attention, front and centre. This gives scraper developers the information they need to keep the data flowing. We could add a touch of gamification to the copy to reward people for reducing the list ;)

We could also show a list of scrapers the person is watching (owned by others only?) so that they get more connected to other people on morph.io and get reminded of the interesting stuff they've found.

**Comment by equivalentideas** [comment]
I'm now going to do some sketches of what these different bits could be like.

**Comment by equivalentideas** [comment]
Here's an idea for what the search banner form could be like:
![2015-05-05 12 09 19](https://cloud.githubusercontent.com/assets/1239550/7466064/188ce4f4-f320-11e4-9b10-fd300234023a.jpg)

Here's how this could sit in a banner on the page:

![2015-05-05 12 15 12](https://cloud.githubusercontent.com/assets/1239550/7466101/b1a34b10-f320-11e4-9350-6d5693f718a3.jpg)

Maybe thinner, and maybe align the form more to the left of the page rather than centre.

It could be in our general banner style. Maybe a lighter or no background colour.

**Comment by mlandauer** [comment]
:+1: I think this nicely summarises where we got to yesterday

I think some of those search examples should highlight scrapers for some of the non-english speaking countries where there are a lot of morph.io users (e.g. germany, spain) - it would also be good to include non-european examples I think.

**Comment by equivalentideas** [comment]
> I think some of those search examples should highlight scrapers for some of the non-english speaking countries where there are a lot of morph.io users (e.g. germany, spain) - it would also be good to include non-european examples I think.

Agreed. I did a bit of searching and thought **[Parliament](https://morph.io/search?utf8=%E2%9C%93&q=Parliament)** was a really nice one with:

> Malaysian Parliament Hansard URL
> Hungarian Parliament Spending Contracts
> Members Of Finnish Parliament Scraper
> Slovak parliament session transcripts database
> Members of the Tanzania Parliament
> Members of Parliament in Ghana
> MEPs at the European Parliament
> QLD Former Members of Parliament

I went "wow!" :)

I think three is a good number, but not sure about the other two. What do you think about highlighting the domain option if that's working well?

**Comment by equivalentideas** [comment]
Here's an idea for the 'Scrapers that need your attention list.

First pass just a regular list of scrapers, but with a heading like '9 scrapers need your help' or '—need your attention'.

![screen shot 2015-05-05 at 2 25 05 pm](https://cloud.githubusercontent.com/assets/1239550/7467044/00a74de4-f333-11e4-9b1d-cdf70aaa9b3e.png)

Then as a second iteration you could add some more context about the error in a section at the bottom of each scraper item, with information about when it first failed, and when it last failed to help distinguish errors you've need or prioritise which to look at. Messy sketch:
![2015-05-05 14 25 52](https://cloud.githubusercontent.com/assets/1239550/7467081/aefdc8fa-f333-11e4-9a23-62277c088b71.jpg)

The would probably be better as something like 'Last failed 15min ago – failing since 9 days ago'.

**Comment by equivalentideas** [comment]
@mlandauer I'll now move on to the 'scrapers that need your attention' list and break that out into an issue. Sounds good?

**Comment by mlandauer** [comment]
Yup!

**Comment by equivalentideas** [comment]
@mlandauer we've implemented a first pass on the three ideas we originally had, and made some new issues stemming from those. I think we close this ticket and make new ones for specifics when they arise. I'll close this are reopen if you disagree.
