### ISSUE TITLE
Scraped domains seems wrong

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#700]
This scraper apparently `Scrapes ebiz.campbelltown.nsw.gov.au` https://morph.io/tporetro/oilfield130430 but looking at the code that doesn't make sense https://github.com/tporetro/oilfield130430/blob/master/scraper.py

**Comment by henare** [comment]
Here's another weird one: https://morph.io/agusmu/top_free_android_apps

**Comment by mlandauer** [comment]
The way that morph figures out which scraper is responsible for which connections, is that it records the source ip address and each run records the ip address of the associated container.

Then, when a new connection is recorded with a particular ip address, morph just looks up the most recent run that was using that ip address.

In this case, that's likely wrong and the most likely reason I can think of is that we are deleting broken runs at the moment as emergency surgery for the weirdness that we've been seeing on the server today.

**Comment by mlandauer** [comment]
I'm going to close this as the two examples were run 2 and 4 months ago. If you find something more recent please reopen the ticket
