### ISSUE TITLE
Redirect login to home page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#705]
The home page is a better landing page than a profile page for new users because they can search and we can better present them with actions from this page.

@mlandauer I see there's something a bit tricky going on in the application controller with this, I think you might be able to make this change more confidently :)

**Comment by mlandauer** [comment]
I think we should do this as soon as we add an action to the landing page for new users who don't have any scrapers to create a scraper.

**Comment by equivalentideas** [comment]
Sounds good :+1:

**Comment by mlandauer** [comment]
I can certainly pick this up. No worries.
