### ISSUE TITLE
Show scrapers that need attention on the logged in landing page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#706]
Comments extracted from #698 :

*As a current user, when I log into morph.io, I want to know about scrapers that need my attention, so that I can fix them and keep getting the data I need.*

The obvious thing to do here is show a list of scrapers that need attention, front and centre. This gives scraper developers the information they need to keep the data flowing. We could add a touch of gamification to the copy to reward people for reducing the list ;)

We could also show a list of scrapers the person is watching (owned by others only?) so that they get more connected to other people on morph.io and get reminded of the interesting stuff they've found.

Here's an idea for the 'Scrapers that need your attention list.

First pass just a regular list of scrapers, but with a heading like '9 scrapers need your help' or '—need your attention'.

![screen shot 2015-05-05 at 2 25 05 pm](https://cloud.githubusercontent.com/assets/1239550/7467044/00a74de4-f333-11e4-9b1d-cdf70aaa9b3e.png)

Then as a second iteration you could add some more context about the error in a section at the bottom of each scraper item, with information about when it first failed, and when it last failed to help distinguish errors you've need or prioritise which to look at. Messy sketch:
![2015-05-05 14 25 52](https://cloud.githubusercontent.com/assets/1239550/7467081/aefdc8fa-f333-11e4-9a23-62277c088b71.jpg)

The would probably be better as something like 'Last failed 15min ago – failing since 9 days ago'.

**Comment by mlandauer** [comment]
One thing that I've failed to mention in the discussions so far on this idea is that the scrapers it should show are not just ones that you own (or belong to an organisation of which you are part). You can "watch" any scraper, user or organisation. See for example the scrapers watched by me https://morph.io/users/mlandauer/watching

**Comment by equivalentideas** [comment]
> he scrapers it should show are not just ones that you own (or belong to an organisation of which you are part)

Love that because it promotes collaboration :+1:

**Comment by mlandauer** [comment]
Also we should rejig the email alerts and this section to behave and look very similar

**Comment by equivalentideas** [comment]
I'm gonna go for a first pass at this:

Just a simple list of scrapers with a heading.

The list will have your erroring scrapers + those of orgs you're a member of + those you follow

**Comment by mlandauer** [comment]
@equivalentideas as a first pass look at how the email alerts are generated and follow that please

**Comment by equivalentideas** [comment]
Thanks

**Comment by mlandauer** [comment]
Sorry let me make that a bit clearer. Follow the logic of the email alerts in terms of which scrapers are shown and in which order. Otherwise, design the list to look and behave how you think is best (ignoring the email alerts). Then at a later stage we can make the email alerts look the same as that list.

Little clearer now?

**Comment by equivalentideas** [comment]
Much thanks :) are you talking about in mailers/alert_mailer.rb I'm finding it a bit confusing how that's working (never looked at mailer ruby before). I'll see if I can work it out for a tick and ask you any questions if I get stuck.

**Comment by equivalentideas** [comment]
Ok so I think I get it more now after looking at how broken_runs and all_scrapers_watched are generated in the user model.

It appears that we don't currently have a method for getting all the unique failing scrapers from all_watched + user.scrapers . But if you haven't watched something, or you've unwatched one of your own scrapers, do you want to see it here? Maybe it would be better for people to watch their own scrapers?

**Comment by equivalentideas** [comment]
Currently the process for getting failing scrapers from all_scrapers_watched is handled in the process_alerts method. I'm going to make a new method for getting scrapers_needing_attention to use for this list.

**Comment by equivalentideas** [comment]
The broken runs are connected back to their scrapers and sorted in alert_mailer. I'll copy that logic into the new scrapers_needing_attention method.

**Comment by mlandauer** [comment]
We should only be showing people the failing scrapers from their watch
list. It's a separate issue that people aren't by default watching their
own scrapers.

It's important that we do it this way that we allow people to not watch
some of their own scrapers if they don't want to. Makes it the most
flexible for users.

**Comment by equivalentideas** [comment]
> We should only be showing people the failing scrapers from their watch
list. It's a separate issue that people aren't by default watching their
own scrapers.

That sounds very sensible :)

**Comment by mlandauer** [comment]
See https://github.com/openaustralia/morph/issues/275

**Comment by mlandauer** [comment]
@equivalentideas Would you mind if you were to put this issue aside for the time being? I think this would be a good one to work through together on Friday maybe?

I think the ticket to add the "Create you first scraper" action for people without scrapers would be a good quick one.

And then it would be awesome to get the "showing the downloads" ticket done and dusted. I think the main thing there that I need from you is to figure out how the user should be warned about their download being displayed.

**Comment by equivalentideas** [comment]
That sounds good to me :+1:

**Comment by equivalentideas** [comment]
Title: 9 scrapers you are watching need help

end with 'manage your watched scrapers'

**Comment by equivalentideas** [comment]
Here's the basic list on the page, without the error data included:

![screen shot 2015-05-11 at 11 57 05 am](https://cloud.githubusercontent.com/assets/1239550/7557456/0f392926-f7d5-11e4-9c19-4fd8e114d976.png)
![screen shot 2015-05-11 at 11 57 28 am](https://cloud.githubusercontent.com/assets/1239550/7557457/0f3deaba-f7d5-11e4-83f0-9913ed577cb7.png)

**Comment by equivalentideas** [comment]
Here's a basic 'panel-footer' style for the into. Seems a bit too dominant of the list item atm:

![screen shot 2015-05-11 at 12 12 24 pm](https://cloud.githubusercontent.com/assets/1239550/7557557/1c2aa93c-f7d7-11e4-940b-054c4ec24717.png)

**Comment by equivalentideas** [comment]
A little smaller, red text to match the label:

![screen shot 2015-05-11 at 12 16 03 pm](https://cloud.githubusercontent.com/assets/1239550/7557584/93747eb4-f7d7-11e4-8c0e-394cd97c4900.png)

**Comment by mlandauer** [comment]
@equivalentideas I like where this is going

**Comment by equivalentideas** [comment]
Less padding and lighter background:
![screen shot 2015-05-11 at 12 23 40 pm](https://cloud.githubusercontent.com/assets/1239550/7557641/af5ea9be-f7d8-11e4-879c-fec0e24e155b.png)

**Comment by equivalentideas** [comment]
@mlandauer what do you think about removing the errored label scrapers in this list? It seems to me like dupe info that's noise here.

**Comment by mlandauer** [comment]
We should also consider what happens when:
1. All the scrapers that a user is watching have recently run successfully
2. The user isn't watching anything

For 1 I think we should have a message to that effect - essentially congratulating the user. Note we could use similar wording to what's in the email alerts now. e.g. "65 scrapers you are watching are working. These 5 have a problem"

For 2 maybe something like the ["blank slate" UI pattern](http://ui-patterns.com/patterns/BlankSlate) which shows the user what happens if they watch their own and other scrapers.

**Comment by mlandauer** [comment]
First things first, make the language consistent with the rest of the site. Nowhere else do we refer to things as "failed". We refer to them as "errored" in the main ui and in the email alerts.

So, I think before you consider doing anything else you should do that and then we can see whether the labels are still needed.

**Comment by equivalentideas** [comment]
On the [scraper page](https://morph.io/planningalerts-scrapers/leichhardt) we say "Last run failed about 2 hours ago". I think that's what we want the wording to be consistent with, as you'll click through and look for that message. Maybe "Errored for 9 days – last run failed 2 hours ago"? It is weird that we have two terms.

> For 1 I think we should have a message to that effect - essentially congratulating the user. Note we could use similar wording to what's in the email alerts now. e.g. "65 scrapers you are watching are working. These 5 have a problem"

I think the idea of rewarding them for fixing scrapers is good because that should encourage them to do more. Not sure if you were suggesting this with the wordings, but I don't think we should mention the working scrapers if there are errored ones. It feels like noise to scan past for the users in our story: *As a current user, when I log into morph.io, I want to know about scrapers that need my attention, so that I can fix them and keep getting the data I need.* That way we hold back the reward till all your scrapers are fixed, which makes it more special :) So once all your scrapers are working you get something like "All 7 scrapers you are watching are collecting data." or just 'working' but it feels like an opportunity to focus on the data.

> For 2 maybe something like the "blank slate" UI pattern which shows the user what happens if they watch their own and other scrapers.

Need to think about this one. I agree that this is a great place to put the focus on the value of watching scrapers.

**Comment by equivalentideas** [comment]
>  First things first, make the language consistent with the rest of the site

I've changed it to use 'errored' for the status of the scraper, and 'failed' to describe the run—which seems to me how this works across the site.

![screen shot 2015-05-11 at 2 10 38 pm](https://cloud.githubusercontent.com/assets/1239550/7558433/89e00fca-f7e7-11e4-8867-da1b1592dd3c.png)

**Comment by equivalentideas** [comment]
I'm gonna let that sit and have a look at the 'All the scrapers that a user is watching have recently run successfully' situation.

**Comment by equivalentideas** [comment]
*As a user watching scrapers, when I log into morph.io, I want to know when all the scrapers I'm watching are working, so I start my session on a happy note and I'm encouraged to use morph.io*

@mlandauer do you think this captures the experience we want our citizens to have in the 'all scrapers successful' situation?

**Comment by equivalentideas** [comment]
Here's an idea. Move these sections up to the top of the page, as they are alerts/welcome messages and give them a banner style. here I've checked the warning colour on the 'needs help' banner, as the red seemed a bit red alert and could be fatiguing if it's there too often.

'has errored watched scrapers':
![screen shot 2015-05-11 at 2 58 55 pm](https://cloud.githubusercontent.com/assets/1239550/7558732/5f0e56b0-f7ee-11e4-87bf-3c3f8c931ec7.png)

'all watched scrapers are working'
![screen shot 2015-05-11 at 2 59 12 pm](https://cloud.githubusercontent.com/assets/1239550/7558733/5f0ffff6-f7ee-11e4-982a-1415c24fc503.png)

**Comment by equivalentideas** [comment]
Talking with @mlandauer we think that the banner style under the nav is too heavy, it makes the search block move around which is a bit disconcerting and frames the page with this information which ins't intended.

This list is now only going to show scrapers that became errored in the last 25 hours, so it's no longer useful to distinguish between when a scraper first errored and when the most recent run was. We'll change the error info text to just 'Errored for $time-ago'.

Moving on with this we'll break the implementation and deployment into iterations:

1. errored scrapers list
2. successful scrapers confirmation and praise message
3. prompt to watch some scrapers

I'm moving on with the next pass at the static prototype for the errored list.

**Comment by equivalentideas** [comment]
Here's another pass on the errored scraper alert, using a panel with heading:

![screen shot 2015-05-12 at 12 17 28 pm](https://cloud.githubusercontent.com/assets/1239550/7579060/4bf3624c-f8a1-11e4-8ff1-51407a7123e4.png)
![screen shot 2015-05-12 at 12 19 52 pm](https://cloud.githubusercontent.com/assets/1239550/7579064/513e4622-f8a1-11e4-812e-9fc127c70024.png)

I think this is much nicer as it's a discrete box that has appeared to tell you something, something you should respond to. The panel style separates it from the rest of the page.

**Comment by mlandauer** [comment]
:+1:

**Comment by equivalentideas** [comment]
Thanks for that @mlandauer . I'll move on to implementing this first iteration.

**Comment by equivalentideas** [comment]
Stage 1 merged by https://github.com/openaustralia/morph/commit/227314b98e5361fc641d0d0f322b264cdc97393a

We should break the success and no watching situations into new issues I think.

**Comment by equivalentideas** [comment]
I've extracted those two situations into #730 and #731 so I'll close this. Please reopen if necessary :)
