### ISSUE TITLE
Help citizens without scrapers create their first on the landing page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#707]
Comments extracted from #698 

**As a new user, when I visit the landing page, I want some help to write my first scraper on morph.io, so that I can get the data I need.**

We don't really have any documentation of how to write a scraper. We depend on people already knowing how or being skilled enough to work it out by looking at the templates/other scrapers.

We're not planning to add any new how-to's at this point, but we could ease people into adding a scraper, and hopefully with determination will prevail.

We had an idea that you could add a scraper from the landing page if you had none—by entering a description and title for it. We could give some direction for a good description and require it. That way, even if people can't follow through and write the scraper, they can make a repo to describe what they're after. This is a good first step for them, would be very interesting experiment, and there may be a way to then connect people who are interested to pick up those scrapers and write them.

**Comment by equivalentideas** [comment]
From @mlandauer in chat:

> How about we keep that super simple and it just is a link to “new scraper” page? (edited)
> With some simple text like “Create your first scraper”?

**Comment by equivalentideas** [comment]
Moving onto this now

**Comment by equivalentideas** [comment]
as suggested above, I think we could do this as a heading and button:

### Unlock the data you need
### [Create your first scraper]()

Aiming for simple, focused on the value to the citizen, consistent with copy on logged out front page, personal.

**Comment by mlandauer** [comment]
:+1:

**Comment by equivalentideas** [comment]
Here's this basically dropped in with a little stying:
![screen shot 2015-05-06 at 5 08 19 pm](https://cloud.githubusercontent.com/assets/1239550/7488820/9d5edece-f412-11e4-82ec-ce2ba6d47c3e.png)

Here's a version with longer, more specific text which I think suits the layout a bit better because it follows the short long pattern of the search box:

![screen shot 2015-05-06 at 5 17 46 pm](https://cloud.githubusercontent.com/assets/1239550/7488922/f856c070-f413-11e4-85ac-0f43fb76e9dc.png)

**Comment by equivalentideas** [comment]
I'm going to do a quick sketch of the 'add new scraper' stuff on the righthand side, next to the search form.

**Comment by equivalentideas** [comment]
I was originally thinking a full width banner for each action ('search', 'add new scraper') but I feel like it's too sparse with the layout above. Here's a sketch of the 'Create you ...' block on the righthand side:

![2015-05-06 17 39 30](https://cloud.githubusercontent.com/assets/1239550/7489176/43fe8cbc-f417-11e4-85ec-e64a7c5cec7c.jpg)

The layout feels more balanced, but there's less of a progression from step one, search, step two, add a scraper.

**Comment by equivalentideas** [comment]
I think I'm going to do the dumb thing first and push the simple left aligned layout to a PR and we can work on it there.

**Comment by mlandauer** [comment]
@equivalentideas sounds good!

**Comment by mlandauer** [comment]
@equivalentideas I see what you're saying about the different layout options. I think it's not massively clear at this stage what the best thing to go with is.

Maybe we should just stick with the simplest option that you put in #709 and see how things develop as we work more on the landing page

**Comment by equivalentideas** [comment]
Thanks @mlandauer I think that's a good call.
