### ISSUE TITLE
Search filter for scrapers with some data

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#712]
The idea has come up of allowing sorting of scrapers in search results by the amount of data they have. The problem with this is that more data is not necessarily better than little data. What's really important is whether the scraper has any data at all as occasionally people will start writing scrapers but not actually get to the point where it writes anything in the database.

So, it would be good to by default filter scrapers by whether they have any data.

Something like
"Only show scrapers with data"

And a checkbox that is by default on.

**Comment by equivalentideas** [comment]
I think this would be really helpful. A couple of thoughts:

What if you do a search but there are no scrapers with data. Could we somehow show the number of scrapers that don't have data in a little badge like the 'scraper/user' search nav?

I think a button interaction is usually simpler than a checkbox (particularly for touch screens), as it's a clearer target and has very clear 'take me there' interaction.

We could should the count of 'all scrapers' in the button or something.

![screen shot 2015-05-08 at 9 06 52 am](https://cloud.githubusercontent.com/assets/1239550/7527692/9d727128-f561-11e4-9d70-321f8d1975c7.png)

**Comment by equivalentideas** [comment]
Is the way to do this to add a scope to the scraper model with `where.not("sqlite_db_size = '0'")` ?

**Comment by equivalentideas** [comment]
Current thinking for simple first iteration is:

* buttons under the scraper tab
* buttons have no counts

Will do a sketch later when I come to this.

**Comment by equivalentideas** [comment]
The buttons on small screens:

![screen shot 2015-05-12 at 4 54 01 pm](https://cloud.githubusercontent.com/assets/1239550/7581541/925ac59c-f8c7-11e4-9905-a0ca6e324573.png)

**Comment by equivalentideas** [comment]
For wider screens, small tablets and larger, having the button to change on the inside becomes un-ergonic as you want to tap it with your thumb. So you want to move it to the righthand side, so the all scrapers button is on the edge of the screen. Having it small on the left also gives us a lot of wasted space to the right.

![screen shot 2015-05-12 at 4 58 49 pm](https://cloud.githubusercontent.com/assets/1239550/7581617/b4d9284c-f8c8-11e4-901c-f601aa577d2d.png)

I think moving it up inline with the type options would be nice. Still clear, very reachable and out of way of the results.

![screen shot 2015-05-12 at 5 04 40 pm](https://cloud.githubusercontent.com/assets/1239550/7581652/1baed58a-f8c9-11e4-847b-105237178438.png)

**Comment by equivalentideas** [comment]
Here's what that looks like.
![screen shot 2015-05-12 at 5 37 03 pm](https://cloud.githubusercontent.com/assets/1239550/7582139/1e94ccb4-f8ce-11e4-8517-36e9caadd65c.png)
![screen shot 2015-05-12 at 5 37 13 pm](https://cloud.githubusercontent.com/assets/1239550/7582140/1e9a9d4c-f8ce-11e4-9a1d-50e3e9ec5011.png)
I'm not sure about it because of the line underneath from the tab pattern. Going to live with it while.

**Comment by equivalentideas** [comment]
The trickiest thing with this is what happens when there are scrapers, but none have data. Do you get:

1. A notice that there were no scrapers with data for the results x
2. You get the all scrapers option instead
3. The filters are removed and you get pushed to all scrapers

Typing this out, I think 1 is the most predictable, simplest.

**Comment by equivalentideas** [comment]
Should you see the filters option if there are no scrapers at all. I don't think so as then you'll go click on them for nothing.

**Comment by equivalentideas** [comment]
Almost there with this but then started getting some weird results returned. I needed to specifically included a check for data in the search index, not just as a query on the search, for searchkick to pick it up properly, then reindex.
