### ISSUE TITLE
Problems with uploading to S3 via SSL

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#734]
See this tweet from @pudo https://twitter.com/pudo/status/599928602604478464 and #733.

Yes, morph intercepts SSL as well as regular http to get stats on number of pages scraped, as well as the amount of data sent and received. It uses mitmproxy to do a "man-in-the-middle attack" and the CA certificate used for signing is embedded in the container that all the scrapers run on.

I definitely want to help you get your issue fixed @pudo as soon as possible. It would be great if you could supply a failing bit of minimal code that I can use for testing - something that fails on morph but works when you run it locally. Then I can test it on a local VM with and without the proxying and see if the problem is due to mitmproxy.

Thanks!

**Comment by pudo** [comment]
Thanks for looking into this, @mlandauer! Here's the most reduced version of the problematic code:

https://gist.github.com/6057d06676aa5f83d72d

It's worth mentioning that in the failing scraper the text (line 14) is about 3-4MB of JSON. Works locally, but not on morph.

**Comment by mlandauer** [comment]
Here's progress so far:
* Replicated that the script works fine when run on my local box
* Replicated that the script hangs when run on morph.io (https://morph.io/mlandauer/morph_s3_test_upload)
* By adding a few print statements, it looks like `conn.get_bucket` works fine but it hangs when running `k.set_contents_from_string`
* By looking at `connection_logs`
For the latest run (97585):

method | scheme | path | request size | response size | domain id | response code
---------- | ---------- | ------ | ----------------- | -------------------- | ------------- | ---------------------
HEAD | https | / | 0 | 0 | 3746 | 200
PUT | https | /popolo-test.txt | 13 | 0 | 3746 | 100
PUT | https | /popolo-test.txt | 13 | 0 | 3746 | 100
PUT | https | /popolo-test.txt | 13 | 0 | 3746 | 100

You can see the first successful api call that returns 200. The following api call is return code 100 and then retrying.

This issue on mitmproxy looks suspiciously related https://github.com/mitmproxy/mitmproxy/issues/553

**Comment by mlandauer** [comment]
This is now rolled out to production and you can see that the test case scraper https://morph.io/mlandauer/morph_s3_test_upload finishes without any issues.

So @pudo you should be good to go!

Do let me know if you run into any other issues.

**Comment by pudo** [comment]
Wow, that is some kick-ass support. Thanks @mlandauer -- buy you a beer in Ottawa?
