### ISSUE TITLE
Scroll bar visible next to filter buttons

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#737]
Firefox on Linux, of course:

![selection_001](https://cloud.githubusercontent.com/assets/48945/7677260/cf688dca-fd4a-11e4-8218-a08c80e6bb6a.png)

**Comment by equivalentideas** [comment]
Thanks for catching this @henare 

This is related to using ['overflow' to property to hide the heading on small screens](https://github.com/openaustralia/morph/blob/master/app/assets/stylesheets/search.css.scss#L35).

I can't reproduce this on my machine, could you please try changing the [overflow value for wide screens](https://github.com/openaustralia/morph/blob/master/app/assets/stylesheets/search.css.scss#L40) to visible or hidden and see what the impact is?

Either of those values should be fine for the layout, but I'm not sure if they will fix this bug.

**Comment by henare** [comment]
>I can't reproduce this on my machine, could you please try changing the overflow value for wide screens to visible or hidden and see what the impact is?

Both those work.

**Comment by equivalentideas** [comment]
Great thanks for that :+1:
