### ISSUE TITLE
[meta] investigate namara.io

### ISSUE THREAD

**Issue by patcon** [openaustralia/morph#742]
These guys work with open data. I'm a big supporter of them and what they do (as open data consultants), but I still thought I should put them on your radar in case you can learn anything from how they're making open data sets available via versioned API:

http://namara.io/#/api

**Comment by mlandauer** [comment]
I'd like to understand what it is you most like about the api. Is it that it provides access to versions of the underlying data?

**Comment by patcon** [comment]
I suppose that I liked that it seemed more like other API's I'm used to working with. But now that you're asking, perhaps the SQL query approach morph.io takes is more flexible, since any language has good good querybuilders -- less need for custom client libraries

Would strike me as hard to rate-limit on your end though, as you can't control for harsh queries (?)

Anyhow, I'll be using namara.io for a project soon, so I'll let you know if I have thoughts after more hands on time. Thanks!
