### ISSUE TITLE
Google webmaster tools is picking a *lot* of urls that it can't find

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#745]
They seem to be related to the sync gem. Some example urls

* https://morph.io/59c5e3a1f4e317028432ea5334c0f2e72e9f2a0d-end
* https://morph.io/59c5e3a1f4e317028432ea5334c0f2e72e9f2a0d-start

**Comment by henare** [comment]
>They seem to be related to the sync gem.

Yeah, this was injected to a scraper page on my development instance:

    <script type='text/javascript' data-sync-id='/b2119ad01ebc86291100d581e647c7cc434a1c47-start'> Sync.onReady(function(){ var partial = new Sync.Partial({ name: 'show_partial', resourceName: 'scraper', resourceId: '16', authToken: '/b2119ad01ebc86291100d581e647c7cc434a1c47', channelUpdate: '/b2119ad01ebc86291100d581e647c7cc434a1c47-update', channelDestroy: '/b2119ad01ebc86291100d581e647c7cc434a1c47-destroy', selectorStart: '/b2119ad01ebc86291100d581e647c7cc434a1c47-start', selectorEnd: '/b2119ad01ebc86291100d581e647c7cc434a1c47-end', refetch: true }); partial.subscribe(); }); </script>

So I'm guessing Google sees those and says, "Ooh! URLs. Omnomnomnom". Except they're not URLs, they're the channel IDs sent to Faye :-/

I guess we should just disallow them in `robots.txt`.

**Comment by mlandauer** [comment]
Is there anything in the sync documentation about that? It feels kind of
icky to just disallow them in robots.txt and also liable to exclude the
wrong things

**Comment by henare** [comment]
>Is there anything in the sync documentation about that?

Not that I've seen.

>It feels kind of icky to just disallow them in robots.txt and also liable to exclude the wrong things

I agree. I also think it would be *very* hard to write a rule to do it too, e.g. the `authToken` is just a 41 character hex string.

This is just Google getting it wrong. It's guessing those URLs from markup that does not indicate they're URLs. It's [trying to be smart](https://support.google.com/webmasters/answer/2409439?ctx=MCE&ctx=NF):

>Generally, **404 errors don’t impact your site’s ranking in Google**, and you can safely ignore them. Typically, they are caused by typos, misconfigurations (for example, for links that are automatically generated by a content management system) **or by Google’s increased efforts to recognize and crawl links in embedded content such as JavaScript**.

Emphasis above it mine. I think it indicates we don't worry about this.

**Comment by mlandauer** [comment]
Can we document this weirdness somewhere and close this?

**Comment by henare** [comment]
Should we document it upstream in the Gem or were you just thinking our README?

**Comment by mlandauer** [comment]
I don't know. Whatever is sensible, I guess. What do you think?

**Comment by henare** [comment]
I think it would be helpful to send something upstream.

I'm not sure where to document it for us. It would be great if we could add something to Webmaster Tools, since that's where you find the problem. Maybe having this closed issue is enough?
