### ISSUE TITLE
List of github organizations is out of date

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#750]
I want to use the API key for a github Organization I'm part of ([everypolitician](https://github.com/everypolitician)) — but even though I've updated my membership of it to be public (and verified I can see it on my account on github when I'm not logged in), it's not appearing on my Morph page, and trying to go directly to https://morph.io/everypolitician 404s.

**Comment by mlandauer** [comment]
@tmtmtmtm you might need to log out and log back in for that to update. Give that a go and see if it works.

**Comment by henare** [comment]
Related to #397?

**Comment by tmtmtmtm** [comment]
Yep — logging out and in again did the trick. Thanks.

**Comment by henare** [comment]
Maybe if you're logged in and looking at your profile page there should be a little refresh icon next to the list of organisations that does this for you?
