### ISSUE TITLE
Fetching repo list from Github is hanging

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#772]
https://morph.io/scrapers/new/github is getting stuck at the "Hang on. Getting your repositories from GitHub…" stage (has been like this for at least an hour or two now)

**Comment by tmtmtmtm** [comment]
This still isn't working. I can create new scrapers fine, but I can't tell Morph about existing ones.

**Comment by equivalentideas** [comment]
Confirmed this isn't working for me either

**Comment by mlandauer** [comment]
@equivalentideas can you check if this is working in development locally and if not what the logs say?

**Comment by equivalentideas** [comment]
@mlandauer on it

**Comment by equivalentideas** [comment]
aha, it's a javascript error:

> Uncaught Error: No element option passed to Waypoint constructor application-dfc46fa7e252f7551b756ff0d07655fd.js:7

**Comment by equivalentideas** [comment]
I'm pretty sure this will be a problem with calling the animation script I wrote last week. Debugging now.

**Comment by equivalentideas** [comment]
Yep found the problem about to push fix

**Comment by mlandauer** [comment]
@tmtmtmtm just deployed the fix to production. It looks to me like it's all working again.

**Comment by tmtmtmtm** [comment]
Yep — all working fine now! Thanks!
