### ISSUE TITLE
Add new quote from Wendy Bacon on the landing page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#774]
I think we should have the current two quotes plus this new one from Wendy Bacon because it **so good**

> [If you're a paid or citizen journo or student journo & you don't know about this, it's time to get acquainted with https://morph.io/](https://twitter.com/Wendy_Bacon/status/604190077439213568)

Show her as:

Professor Wendy Bacon,
Journalist, Activist
Australia

**Comment by equivalentideas** [comment]
A grand idea
