### ISSUE TITLE
My scraper keep running after it finished

### ISSUE THREAD

**Issue by thevtm** [openaustralia/morph#781]
[Scraper Page](https://morph.io/thevtm/CartolaFCScraper)

I run the scraper one day as I have done several times before.
It run as it always does, the status said it was running, the console messages was ok, then it finished.
The status wasn't indicating that it was running anymore.
But ~5 minutes later, out of nowhere the console messages start rolling again, indicating that the scraper was running (the status didn't indicate that it was running).
I have tried to run and stop. Doesn't work.
It is running right now, and I can't stop it.
I don't know what to do anymore.
![image](http://cdn.dejanseo.com.au/fun/google-skynet/skynet-thumb.jpg)

```
Injecting configuration and compiling...
 Injecting scraper and running...
 [LOG] Downloading Scouts Iniciado
 [LOG] Baixando   1 / 41
 [LOG] Baixando    2   /   41 
 [LOG] Baixando   3 / 41

...

 Injecting configuration and compiling...
 Injecting scraper and running...
 [LOG] Downloading Scouts Iniciado
 [LOG] Baixando  1 / 41
```

**Comment by thevtm** [comment]
Update:
I haven't changed anything.

The status is that it is running.

    The scraper is running. It was queued automatically about 24 hours ago.

By the console information it is stuck (not running over and over again).

I've tried to stop it (by clicking on *Stop scraper*) but it doensn't work.

**Comment by thevtm** [comment]
It seems to be working now.

**Comment by mlandauer** [comment]
Hi @thevtm - sorry about the hassle you were having and that I haven't been able to get back to you sooner. We've been doing some pretty big reengineering of the morph.io backend that is making the running of scrapers even more reliable - especially for scrapers that run a long time. So, hopefully this shouldn't be an issue you see again.

If you see any other problems please don't hesitate to open another issue. It's very helpful for us to get any feedback.

And of course if there are any features you would love to see in morph.io then please open an issue for that too. Thanks again!

**Comment by thevtm** [comment]
Thank you for your response.
I've been using morph for a while and I really enjoyed.
Keep up the good work. :thumbsup:
