### ISSUE TITLE
URGENT Upcoming github api changes will break things on morph on June 24

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#783]
We need to update things before then! Eek.

See https://developer.github.com/changes/2015-06-10-breaking-changes-to-organization-permissions-coming-on-june-24/#migration-period

**Comment by henare** [comment]
We need to switch the API call we're using:

>If your app only needs to fetch the user’s public organization memberships, you should use the [List user organizations](https://developer.github.com/v3/orgs/#list-user-organizations) API instead. Since that API only returns public information, it does not require any scopes.
