### ISSUE TITLE
Update home page meta description

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#787]
>Get structured data out of the web. Code collaboration through GitHub. Run your scrapers in the cloud.

We have more awesome words on the home page, we should translate these onto the meta description tag too.

**Comment by snoblenet** [comment]
Current description

> 'Get structured data out of the web. Code collaboration through GitHub. Run your scrapers in the cloud.'

(102 characters including spaces)

Any reason we're not using keywords too?

For a description, I'd recommend:

- No longer than 160 characters including spaces, so it's displayed and read in full in search results
- Shift focus from what it is to what benefits it provides (while still saying enough about what it is to add credence to any claim to provide benefit)
- A balance between technical benefits (e.g. those associated with running the scrapers in the cloud) and social benefits (e.g. getting access to data that governments don't necessarily want to be easy to obtain)

Taking a lead from the existing home page text, I'd suggest something like:

> Hassle-free web scraping. Over 5000 free public scrapers, or write your own in Ruby, Python, PHP, Perl or Node. Push to the cloud and then set and forget.

(155 characters including spaces)

BTW I ran morph.io and scraperwiki through a few common SEO keyword research engines but the low volumes of organic search traffic for both meant that these tools provided few insights. For scraperwiki, much of the organic search traffic seemed to be related to specific interesting blog posts.

**Comment by henare** [comment]
@snoblenet great stuff :+1: that sounds good to me.

**Comment by snoblenet** [comment]
Great -- I'll submit a PR as soon as I've finished with this randomisation issue
