### ISSUE TITLE
Javascript support would be awesome

### ISSUE THREAD

**Issue by mithro** [openaustralia/morph#791]
@rjwright and @dpschramm both want it.

nodejs would work, so would something like PhantomJS or even a headless Chrome.

@mlandauer

**Comment by tmtmtmtm** [comment]
PhantomJS support already exists — see for example https://morph.io/tmtmtmtm/cabo-verde-assembleia-nacionale and https://morph.io/tmtmtmtm/angola-national-assembly

**Comment by mlandauer** [comment]
Nodejs support was recently added. Also, phantomjs is available from all languages as the phantomjs binary is installed.
