### ISSUE TITLE
node.js scraper fails while installing dependencies.

### ISSUE THREAD

**Issue by kaydensigh** [openaustralia/morph#794]
I put together a basic scraper here:
https://morph.io/kaydensigh/basic_node_js_scraper

While installing dependencies, it fails with:
```
npm ERR! self signed certificate in certificate chain
```
Not sure exactly why, but I think it's to do with sqlite3 needing node-gyp to install.

**Comment by mlandauer** [comment]
I'm pretty sure this should now be fixed by https://github.com/openaustralia/morph/commit/5d23e393bac6ee967702c26a211ef5a7d3468a74
