### ISSUE TITLE
Document how to use phantomjs on morph.io for different languages

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#803]

**Comment by henare** [comment]
Example Ruby scrapers: 

* https://morph.io/tmtmtmtm/cabo-verde-assembleia-nacionale
* https://morph.io/tmtmtmtm/angola-national-assembly

**Comment by henare** [comment]
There's a first pass of this on master with Ruby usage instructions and examples.

**Comment by henare** [comment]
@mlandauer any feedback on what's on master? Is it going in the right direction?

**Comment by mlandauer** [comment]
Haven't had a chance to look yet. Sorry.

**Comment by henare** [comment]
No hurry :)

**Comment by mlandauer** [comment]
Already a big improvement over having no documentation!

Some feedback
* Would be good to give the section of documentation a more user centred title. Maybe something like "how to scrape javascript heavy sites"?
* I think it would be useful to describe how phantomjs is installed on the scraper containers- that it's basically a binary called ... that is available in the path.
* I think it would be great if the example code actually could run and display something. If my understanding is correct it should currently run but won't display anything.
* The examples section still refers to "secret values"

Hope that's helpful :-)

**Comment by henare** [comment]
Super helpful, thanks!

>Would be good to give the section of documentation a more user centred title. Maybe something like "how to scrape javascript heavy sites"?

I totally agree. I've changed the path and title to something along the lines of your suggestion.

>I think it would be useful to describe how phantomjs is installed on the scraper containers- that it's basically a binary called ... that is available in the path.

Done.

>I think it would be great if the example code actually could run and display something. If my understanding is correct it should currently run but won't display anything.

Yes, great idea! I've done this now.

>The examples section still refers to "secret values"

Ahem :-/ Fixed.
