### ISSUE TITLE
tmtmtmtm/san_marino_council is 500ing

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#804]
https://morph.io/tmtmtmtm/san_marino_council won't load at all.

I can fetch the data over the API, but there's a weird encoding issue with it, so I'd guess that there's an error when morph tries to display that…

I was going to blow away the data and rescrape, but I thought it might be useful for you if I left it like this to investigate first.

**Comment by mlandauer** [comment]
Thanks for your patience with this and leaving everything in place. I'm going to take a look at this now.
