### ISSUE TITLE
Run docker tests on Travis

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#806]
They're currently disabled because Docker's not installed. Can we use this to install Docker and run the whole test suite? https://github.com/moul/travis-docker

**Comment by mlandauer** [comment]
Docker is now supported by travis natively but I'm having trouble making it work. When I enable docker by adding:
```
services:
  - docker
```
to `.travis.yml` it then has trouble contacting mysql. If I add the mysql service it makes no difference. Lots of farting around and I can't figure out what's going on.
