### ISSUE TITLE
Give users a public way to financially support morph.io

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#812]
Let's outline the big picture idea here and later we can split bits out into separate issues as we need to.

These ideas came out of a discussion with @henare today.

* Give users the option to financially support morph.io with an option of several support "levels". Each support level is for a fixed amount per month.
* The support level of a user is shown publically on their morph.io profile page
* Each support level comes with a "badge"
* Higher support levels should come with "priority support" which means we answer their questions before other peoples'.
* We could have special levels for organisations supporting
* Highlight users/orgs who are supporting on the landing page - to give them the kudos they deserver
* Add an auto-reply robot that responds to "priority support" users saying how quickly we'll respond. Also, makes it clear what we need to do.
* First level of supporter could be free but you get it when you contribute to morph.io (code, put in a ticket, etc..)

When we've done this we should send a mail out to all users of morph.io to let them know what's new and that they now can "support" morph.io

Possible random ideas for what the levels could be called:
* Open source Supporter, Supporter, Supporter Plus, Priority Supporter
* Micro, Small, Medium, Large
* Names of transformers
* Synonyms of morph
* Names of animated characters that hang out with morph
* Drinks
* Farm animals (to go with the sheep on the landing page?)
* Different kinds of machinery (Tractor, Truck, etc..)
* Bronze, Silver, Gold, Platinum, Unobtanium ($9,999 / month)
* CSV, HTML, PDF
* Free, Hobby, Pro

**Comment by henare** [comment]
Woohoo, the lovely people can become supporters now.
