### ISSUE TITLE
Update pricing page to match new idea of "becoming a supporter"

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#819]
Related to #814

**Comment by mlandauer** [comment]
I've been thinking a bit about this. Here are some options:
1. Remove the pricing page entirely
2. Change the pricing page to say "free" but become a supporter if you can/want and link to the new supporter page
3. Make the pricing link in the menu go directly to the new supporter page. Update the new supporter page to say morph.io is free to use and help keep it free by becoming a supporter.

Thoughts?

**Comment by henare** [comment]
>I've been thinking a bit about this.

Me too!

My first thought was to remove the Pricing page. However when I'm checking out a service for the first time it's often a page I look for straight away (including that wording). I do this because I want to see if it's worth my while investigating this more or if it's too expensive for me to consider.

For this reason I really like 3 because it keeps that wording in the menu but straight away gives you the real story - that it's free but you'd be awesome to be a supporter.

**Comment by mlandauer** [comment]
I'd be happy going with option 3 too. Could you implement this @henare and hide it all behind the same feature flag? (so without the feature flag the pricing page is unchanged)

**Comment by henare** [comment]
Another thing we should change is that currently you need to be signed in to see the supporter page. I think you should be able to see it without being signed in so that you can get a better idea of what it's all about.

**Comment by henare** [comment]
- [ ] Redirect `/pricing` to `/supporter/new` (if feature flag enabled)
- [ ] Update the new supporter page to say morph.io is free to use and help keep it free by becoming a supporter

**Comment by mlandauer** [comment]
Be careful with using a redirect based on a feature flag. Some browsers are quite aggressive in caching redirects (even if they're temporary rather than permanent ones). Might be better just initially make the menu option point to `/supporters/new` if the feature flag is on

**Comment by henare** [comment]
Cool, thanks for that :+1: I'll take your suggested approach.

**Comment by mlandauer** [comment]
Making the supporters page work well without being signed in is a really good idea and super important! Raises some interesting questions. For example, if the user isn't logged in and they click the "become a supporter on this plan" button, it should probably redirect them to sign in/register which should then on success redirect them back to the supporters page with the stripe form popped up. Hmmm...

**Comment by henare** [comment]
I've split that issue out into #841.

**Comment by henare** [comment]
Done a first pass of what we decided to do in this issue.
