### ISSUE TITLE
Do we want to charge in USD rather than AUD?

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#822]
My feeling at the moment is that we should charge in USD. Most of our users are not in Australia and people are more familiar with USD than AUD as most online services are charged in USD.

I'm pretty sure we can charge in USD with Stripe

**Comment by mlandauer** [comment]
Thoughts on this @henare? Would you be happy switching to USD?

**Comment by henare** [comment]
Yes, I think that makes sense :+1:

**Comment by mlandauer** [comment]
Could you do this @henare? Also, change any wording on the page to make it clear that prices are in USD
