### ISSUE TITLE
On completing transaction show something joyful on the thank you page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#825]
Party poppers, happy children, snow made out of gold and sunshine that explodes in rainbows!

**Comment by mlandauer** [comment]
Or alternatively we could redirect back to the sign up page with a flash message or a modal pop up or something like that

**Comment by henare** [comment]
Overnight I decided I was going to make it redirect to the user profile page (so you can see your shiny new badge). Does that sound like a start?

**Comment by mlandauer** [comment]
I think that sounds good

**Comment by henare** [comment]
Done. Now we need to work out the party poppers :rainbow:

**Comment by mlandauer** [comment]
We have a little bounce animation now. Let's call that done for the time being
