### ISSUE TITLE
Should we add project to Stripe plan IDs?

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#830]
Our test plan IDs are just "standard", etc. Since we can use that Stripe account across our other projects should we change the IDs to "morph_standard"?

**Comment by mlandauer** [comment]
Sounds like a good plan to me!

**Comment by henare** [comment]
Are we happy with "basic", "standard", and "advanced"? Or should we hold off making this change until we're more sure about the names?

**Comment by mlandauer** [comment]
It's not user facing so I'm happy that we stick with those plan names on the backend. I'm sure what's shown on the front end will change ;-)

**Comment by henare** [comment]
:+1:
