### ISSUE TITLE
What is priority support?

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#836]
We need to define this and add the description to the supporter page.

**Comment by henare** [comment]
How about:

>Post any question you have to the forum and we guarantee a response within two working days. You'll also get up to two hours personal assistance per month for scraper help, bugfixes, or feature development on morph.io

**Comment by henare** [comment]
I've added that paragraph to the page.

However that definition was just an idea based on some general discussion a while back so I'm interested to hear what you think @mlandauer.

**Comment by mlandauer** [comment]
Yeah I think that wording is good
