### ISSUE TITLE
Don't require sign in to see new supporter page

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#841]
You should be able to see it without being signed in so that you can get a better idea of what it's all about.

**Comment by mlandauer** [comment]
Copying my comment from #819:

> Making the supporters page work well without being signed in is a really good idea and super important! Raises some interesting questions. For example, if the user isn't logged in and they click the "become a supporter on this plan" button, it should probably redirect them to sign in/register which should then on success redirect them back to the supporters page with the stripe form popped up. Hmmm...

**Comment by henare** [comment]
I've parked a nasty, hacky branch that does this here: https://github.com/openaustralia/morph/compare/signed-out-supporter-page

**Comment by henare** [comment]
Fixed in #841.
