### ISSUE TITLE
I think my giant scraper is breaking your site

### ISSUE THREAD

**Issue by nickjevershed** [openaustralia/morph#844]
Page takes 29+ seconds to load, freezes when loaded. Are you loading in the entire console log? This is potentially very large! I'd provide more detail but can't see what's happening on the page.

[https://morph.io/nickjevershed/aec_party](https://morph.io/nickjevershed/aec_party)

**Comment by mlandauer** [comment]
Yup that would be it. It loads the whole console log when it loads the page. As a workaround limit console output to something **not absolutely gigantic** and rerun the scraper. :-)

**Comment by henare** [comment]
:) Duplicate of #612.

**Comment by nickjevershed** [comment]
Haha, thanks. Will disable console ouput
