### ISSUE TITLE
Rework documentation to centre around the user journey

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#846]
The documentation should centre and follow the user journey, something along the lines of:

* Create a scraper
* Get data off a web page
* Save that data to a database
* Get the data from the API
* Monitor your scrapers
* Fix broken scrapers

**Comment by henare** [comment]
The first thing we need to do is inline the bits of documentation where there's language differences. We're using the familiar pattern from [Slate](http://tripit.github.io/slate/) on the API page, so we should also use this elsewhere in the documentation.

After we do that the page is going to be pretty long so we'll need a better way of navigating it. The fixed sidebar navigation of Slate or [Bootstrap](http://getbootstrap.com/css/) looks like good option to emulate.

**Comment by henare** [comment]
I've futzed around with things and I just wanted to Get Something Done to kick things off. So I figured the little table with the different scraper names in different languages would be an easy one to adapt to the tabbed pattern. Except as soon as I went to do it I realised that it's fine as it is and there's no reason to adopt that pattern if it doesn't fit.

So the next plan is to try and pull bits out of the language specific tabs and add them into the main documentation. The "quick start" sections look like a good place to start.

**Comment by mlandauer** [comment]
Feels to me like you might be approaching it from the wrong end. What if
instead of trying to change a small detail like the language tabs, start
with a big section that can be pulled out of the current content that also
fits into the "user journey" idea?

How about pulling out something like "how to migrate from scraperwiki"?

**Comment by henare** [comment]
Thanks for the suggestion!

However I'm not sure what you mean. By "[pull] out of the current content" do you mean remove/extract from the current content? And if so what "how to migrate from scraperwiki" section do you mean specifically?

**Comment by henare** [comment]
@mlandauer has done a first pass of this, yay :purple_heart:
