### ISSUE TITLE
Time ago tags just showing the date

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#855]
Instead of the friendly "1 week ago" or whatever. e.g. the history here: https://morph.io/henare/google_impact_challenge_wishes

**Comment by mlandauer** [comment]
It's being caused by a javascript error due to the addition of the stripe library. It's super important that we fix this quick!

**Comment by henare** [comment]
Yes!

**Comment by mlandauer** [comment]
Do you want to pick this up or shall I?

**Comment by henare** [comment]
I'm on it.

**Comment by mlandauer** [comment]
Awesome! :-)

**Comment by mlandauer** [comment]
Also, thinking about it... How about we only include the stripe library on the pages where it's actually needed?

**Comment by henare** [comment]
I'm in favour of that in principle.

This was actually our code that caused the crash so may also be a good idea to add a check so this only runs on the supporter page.

**Comment by henare** [comment]
Fix deployed.
