### ISSUE TITLE
New scraper from Github has stopped working again

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#858]
When I select a repo at https://morph.io/scrapers/github it simply redirects back to the same page again, and hasn't created it.

**Comment by henare** [comment]
Fix deployed :rocket: Thanks very much for reporting this problem @tmtmtmtm :boom: Sorry for the inconvenience :dog:

**Comment by tmtmtmtm** [comment]
Excellent, thanks. Everything working perfectly today!
