### ISSUE TITLE
Rename discuss.morph.io to help.morph.io

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#868]
Because it's more about getting help.

**Comment by jmatsushita** [comment]
Unfortunately the help site is down with a 502 Bad Gateway error.

**Comment by equivalentideas** [comment]
> Unfortunately the help site is down with a 502 Bad Gateway error.

Thanks for letting us know @jmatsushita we're on the case!

**Comment by henare** [comment]
@jmatsushita thanks for reporting this, it's back up now.

Strange. The docker container was running and I could even log in to it but for some reason the services weren't responding. I restarted it with `./launcher restart app` and it all started working again :-/
