### ISSUE TITLE
started getting ImportError: No module named bs4

### ISSUE THREAD

**Issue by tubaman** [openaustralia/morph#870]
When I run this scraper: https://morph.io/tubaman/travis-uslakes-info

I get:
```python
Injecting configuration and compiling...
Injecting scraper and running...
Traceback (most recent call last):
  File "scraper.py", line 6, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
```

I have BeautifulSoup4 in my requirements.txt

I would not expect this error since bs4 is part of the default morph.io packages and/or I have it specified in my requirements.txt.

**Comment by mlandauer** [comment]
I've reproduced the error by forking your scraper and running it. At the moment, I'm suspecting it might be related to #589.

**Comment by mlandauer** [comment]
This should be fixed (as a workaround) if you merge in the pull request above. The bug #589 made this very hard to see what was happening. So, obviously it's pretty important that that gets fixed soon.
