### ISSUE TITLE
New scraper from GitHub page doesn't work

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#876]
## Backtrace

    line 10 of [PROJECT_ROOT]/app/views/documentation/_format.html.haml: _app_views_documentation__format_html_haml___501188545208864977_69055740
    line 5 of [PROJECT_ROOT]/app/views/scrapers/github.html.haml: _app_views_scrapers_github_html_haml__1713220288095513756_70928620

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/35868/faults/14070017)

**Comment by henare** [comment]
Fixed in 7053f6da71e050b8d249499dc0ab8c4b12d1b197. Deploying that fix now.
