### ISSUE TITLE
Emails not sent from help forum after a restart

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#881]
I was @mentioned and I didn't get an email. I think I should have.

**Comment by mlandauer** [comment]
I've noticed this too. i probably broke something in upgrading the discourse config. Blargh...

**Comment by mlandauer** [comment]
Oops. Silly me https://github.com/openaustralia/morph/commit/a8854739a0f9a92f93a8bf8729ed65b3f050b01a

**Comment by mlandauer** [comment]
I think I'll try to fix this instead by getting discourse to send mails via cuttlefish! :-)

**Comment by mlandauer** [comment]
Fixed by https://github.com/openaustralia/morph/commit/2c4d3e887a18f845d3ba8244a5b3eeeed4d1390e

**Comment by henare** [comment]
I think this might be happening again - I don't think I got an email for this or other recent posts: https://help.morph.io/t/why-is-my-scraper-being-killed/76/9

**Comment by henare** [comment]
Sending a test email doesn't work: https://help.morph.io/admin/email

May I'll just try a restart?

**Comment by henare** [comment]
Restart didn't help.

SSHed into the docker instance and `ping cuttlefish.oaf.org.au` and it works fine. But the error logs from Discourse say it can't find the host. `su`ing to the `discourse` user and trying the ping again doesn't work - WTF?!

**Comment by henare** [comment]
Permissions being incorrect has something to do with Docker versions and SELinux !~waves hands~!

I rebuilt the Discourse install and all's well (and we're upgraded too).

To do this I had to:
```
iptables-morph-remove
cd /var/docker
./launcher rebuild app
# Wait...
iptables-morph-add
```

**Comment by henare** [comment]
This happened again. Maybe it was because the packages got updated? How annoying.

**Comment by henare** [comment]
It's always a problem after you restart, it seems.

**Comment by henare** [comment]
It was restarted over my holidays and it's working so I'll close this again.
