### ISSUE TITLE
SQLite3::CorruptException: database disk image is malformed

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#884]
@drzax deleted their scraper's database and then this error started happening

https://morph.io/drzax/morph-mp-first-speech

## Backtrace

    line 346 of [PROJECT_ROOT]/lib/morph/database.rb: execute2
    line 242 of [PROJECT_ROOT]/lib/morph/database.rb: changes
    line 258 of [PROJECT_ROOT]/lib/morph/database.rb: table_changes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/35868/faults/14458873)

**Comment by henare** [comment]
@drzax I've manually deleted the corrupt database and so your scraper page is working again.

I've left this issue open since we still need to work out what to do if we see this issue.

**Comment by drzax** [comment]
Cheers.
