### ISSUE TITLE
Visually distinguish "Clear database" and "Delete scraper"

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#886]
![screen shot 2015-08-07 at 09 38 12](https://cloud.githubusercontent.com/assets/57483/9131996/29c0dbf6-3ce8-11e5-9db3-7f05a747bd14.png)

Both of these look the same, are in essentially the same place, and have largely identical "are you sure" popups, but the effects of one are rather more severe than the other.

At least twice now I've managed to completely delete a scraper rather than just emptying it because my brain has no short-cuts to differentiating between them and I wasn't paying sufficient attention. Physically separating them more (even to the left and right of the screen), or even making them each a different colour, would make a big difference for very little effort.

**Comment by henare** [comment]
:+1: :+1: :+1:

I came across this exact same issue a couple of days ago!

**Comment by mlandauer** [comment]
This is what it looks like now 
![image](https://cloud.githubusercontent.com/assets/2221/16508481/a8dae418-3f76-11e6-8063-ebb22498d4d2.png)

Based on that I think we can probably close this now. @tmtmtmtm if you disagree please reopen the ticket.
