### ISSUE TITLE
Randomise sort of heroes on front page

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#893]
Right now it looks to be sorted by sign up date.

**Comment by snoblenet** [comment]
@henare do you mean J. Pablo Pérez Trabucco, Will Ockenden and Professor Wendy Bacon? If you do, these are hard-coded in the view, and we'd need a longer list of heroes somewhere if we wanted to cycle through them randomly on this page.

**Comment by equivalentideas** [comment]
> @henare do you mean J. Pablo Pérez Trabucco, Will Ockenden and Professor Wendy Bacon?

Good question @snoblenet :) It's actually the _Heroes supporters of morph.io_ list at the bottom of the _Logged in version of the homepage_. Totally not clear when we described this issue, but this is what's intended ;-)

Here's a screen grab of the section:
![screen shot 2016-03-14 at 10 23 36 am](https://cloud.githubusercontent.com/assets/1239550/13732126/23d7484e-e9cf-11e5-9bd4-1370e77f1d4f.png)

**Comment by snoblenet** [comment]
OK, cheers. Do you make a subset of your production database downloadable for development?

**Comment by henare** [comment]
@snoblenet we don't currently but I think it's pretty easy to get set up locally with your own data, that's what I do. If you run into any issues please keep logging issues so we can make it better for the next person :smiley:

**Comment by snoblenet** [comment]
sure -- i was just going to grab a bunch of 'heroes' and their icons etc but I'll copy paste that from the web page to development

**Comment by snoblenet** [comment]
The view partial at present seems like it's set up to display all supporters on the hero plan. If you get 1000 hero supporters in the future, then you end up with 1000 icons on the page.

`app/views/status/_featured_supporters.html.haml`:

```
- Owner.supporters(plan).each do |owner|
  %li.owner-item= link_to owner_image(owner, 60), owner
```

`app/models/owner.rb`:

`  scope :supporters, ->(plan) { where(stripe_plan_id: plan.stripe_plan_id) }`

As it seems like there are currently 6 hero supporters, then there are six such icons on the page.

So, my questions are:

- Is my observation correct?
- Are we likely to have many more new hero supporters in the near future?
- If we _are_ likely to get many more new hero supporters in the near future, then when I add a randomisation feature, I'll also ensure we only display six icons at a time, as six seems to look good on the page -- OK?
- If we _are not_ likely to have many more new hero supporters in the near future, then I'd question the value of this change and recommend closing the issue -- OK?

**Comment by equivalentideas** [comment]
> Are we likely to have many more new hero supporters in the near future?

Hey @snoblenet :) I think we would love to have the problem of many more Hero supporters :money_with_wings: though there's no sign we will. We've seen roughly 2k more users sign up since the supporter stuff was added and no new supporters.

So I think the trick is to just randomise the list as is and raise a new issue if that causes problems in the future :)

> If we are not likely to have many more new hero supporters in the near future, then I'd question the value of this change and recommend closing the issue -- OK?

I think we'd still like to randomise it because it's order seems meaningful at the moment. We would like everyone to be celebrated equally in the list :). That's what I understand the intention of the issue to be. Once again we never wrote the *Why* behind this issue :(
