### ISSUE TITLE
Re-consider runtime resource limits

### ISSUE THREAD

**Issue by pudo** [openaustralia/morph#898]
Following on from [this discussion on the help forum](https://help.morph.io/t/why-is-my-scraper-being-killed/76/10) I would like to suggest raising the memory limit for scrapers to 512MB.

To give one example, the [FTS scraper](https://github.com/civicdataeu/fts-scraper) (EU expenditure) needs to download a zipped, 14 MB XML file. There may be constellation of stars, programming languages and streaming interfaces which makes it possible to do a streamed download of such a file, while dynamically unpacking it and then parsing the elements in the file using SAX (the XML is also broken, so we need to run a string regex first, also streaming that somehow while feeding it into the XML parser). This is just insane, makes the code brittle, and costs exponentially more time to implement than the naive solution. Still, I'd argue that processing an XML file should be within the scope of morph.io.

**Comment by tmtmtmtm** [comment]
:+1: 

We've had a few examples too of things just not being possible within Morph due to the low memory limits. (Or, at least, it being more trouble than it's worth to try to figure out how to work around it, compared to just running them elsewhere — a free Heroku dyno has 512MB to play with, for example)

**Comment by mlandauer** [comment]
:+1: to making this change. As 512MB is also the memory limit for Heroku it feels about right. Of course it does make things much more difficult in terms of running the morph server as it means many fewer scrapers can run at any one time which is especially an issue when we have a number of very long running scrapers on the server.

I think this might be a good opportunity to try to think of some smarter ways to handle the memory limits. Maybe we could do something like start with high memory limit and then based on actual memory use during scraper runs start to reduce the memory limit (with some safety factor). That way scrapers with low memory use would "donate" memory to other scrapers.

Just a half baked idea but maybe enough to give someone else a better idea on how to do this! :-)

**Comment by tmtmtmtm** [comment]
What about even just leaving the default the same as it currently is, but having an option to boost it to 512MB on a per-scraper basis? Most people will leave the default as-is, but there's a turbo-mode if you really need it. (That then also provides easy options for offering other amounts later too, possibly for a fee, etc)

**Comment by tmtmtmtm** [comment]
Also, if resources are an issue, perhaps #357 could help? I have a bunch of scrapers that take a long time to run but don't need to run every day.

**Comment by henare** [comment]
[Un/]fortunately we've kind of had the decision made for us - we're out of disk space. Again. #905 

We're totally swamped with other things so there's no possibility of us rethinking the architecture right now which means we're going to need to resize the server again. This means we'll have *plenty* of memory to give our 10 concurrent running scrapers 512 MB and since it feels like the right thing to do I say we do it now (after the server upgrade obviously).

**Comment by pudo** [comment]
Oh, this is great news (clothed in bad news). I'm really thankful for this, as it makes the whole platform a lot more attractive for me :) 

At the risk of sounding like a complexity fetishist: have you explored if there could be any benefit in me giving you an AWS key pair so that you can spin up EC2 or AWS containers rather than actually having to run the scrapers on your own machine? I feel like the value you're providing is in coordination, logging, etc. -- throwing in the compute time is almost an extra :)

**Comment by henare** [comment]
>At the risk of sounding like a complexity fetishist: have you explored if there could be any benefit in me giving you an AWS key pair so that you can spin up EC2 or AWS containers rather than actually having to run the scrapers on your own machine? I feel like the value you're providing is in coordination, logging, etc. -- throwing in the compute time is almost an extra :)

I think this would be awesome and it's something we've discussed before. Sounds a lot like what Travis CI does.
