### ISSUE TITLE
Server disk full

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#905]
The morph.io server has used over 180GB so the disk is 97% full. New Relic told me we had a month to deal with it but overnight the server exhausted its disk space completely.

* [x] Work out a time for the outage
* [x] Write an announcement
* [x] Send the announcement
* [x] Resize the server on Linode
* [ ] Increase the memory limit (#898)

## Work out a time for the outage

Linode estimates 2.5 hours to do the migration.

Google Analytics says in the last month 20% of our traffic has come from Australia, 16% from the UK, and 14% from the US.

## Write an announcement

We want to email everyone to tell them of the outage, thank our supporters, ask for more supporters as we'll no longer be covering our server bill, and tell them of the excellent new 5x increased memory limits (#898).

## Resize the server on Linode

Just log into the console.

## Increase the memory limit (#898)

https://github.com/openaustralia/morph/blob/master/lib/morph/docker_runner.rb#L22-L27

**Comment by equivalentideas** [comment]
**9-10 am Friday morning** seems like the best times during the week based on our visitor stats in Google Analytics.

As @henare notes, this doesn't include API usage. This is something we should look into monitoring so we can better schedule these things in the future. Maybe we can see that somehow now, but I've got no idea how.

**Comment by equivalentideas** [comment]
Here's a draft of an email for review @henare :

https://docs.google.com/document/d/13YELJQmtZeTn1NqlJA4qbUxzib6NTApdxOJtaFhD3xg/edit

**Comment by equivalentideas** [comment]
@henare I can do the export of all users and import that into civic etc.

**Comment by henare** [comment]
>9-10 am Friday morning seems like the best times during the week based on our visitor stats in Google Analytics.

:+1: great, thanks for doing this.

>@henare I can do the export of all users and import that into civic etc.

Yes, please! I'm looking at the email now.

**Comment by henare** [comment]
Email is looking great, good stuff @equivalentideas!

Are you going to send that out?

**Comment by equivalentideas** [comment]
> Are you going to send that out?

Yep, I'll load it and send a test and then send it out if there's no bugs.

**Comment by equivalentideas** [comment]
Email sent.

**Comment by henare** [comment]
```
root@li421-88:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda       379G  185G  191G  50% /
udev            7.9G  4.0K  7.9G   1% /dev
tmpfs           1.6G  276K  1.6G   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            7.9G  7.0M  7.9G   1% /run/shm
cgroup          7.9G     0  7.9G   0% /sys/fs/cgroup
root@li421-88:~# 
```
