### ISSUE TITLE
Consider limiting the number of lines of output your scraper can write

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#919]
We currently have the equivalent of an unlimited scrollback buffer. As it's the cause of many problems, such as #612, I think it could be sensible to put a limit on it.

Generally if you're outputting a crazy number of lines you've stuffed something up and want to stop your scraper and fix it anyway.

**Comment by henare** [comment]
One Passenger process was taking up 10GB just now. I'm pretty sure it's when it tries to respond to a request that has ridiculous amounts of log lines.

**Comment by henare** [comment]
I just checked and a problematic scraper we have currently has 455,837 lines. Another scraper running right now that has lots but seems to be performing OK has 15,019 lines.

Maybe quarter of a million lines is a good compromise?

**Comment by henare** [comment]
Another problematic one has 707,443 lines.

**Comment by henare** [comment]
The problematic ones this morning appear to be https://morph.io/blablupcom/tyru and https://github.com/blablupcom/ntreyt - these both have 95,000 lines but the pages load OK (i.e. the log lines don't seem to be massive.

**Comment by henare** [comment]
We recently had a bunch of scrapers that were infinite loops, spitting out lines during each loop. In this case the scraper can merrily run for 24 hours, outputting a several hundred thousand (so far) lines. The container only runs for 24 hours but then the sidekiq process has to sit there for a lot longer extracting all the log lines. This takes up lots of CPU and available sidekiq job spots.

**Comment by mlandauer** [comment]
In #990 the approach taken was to kill a scraper that had too many lines (whatever we decided that would be). As mentioned in the same PR another approach is to limit the number of lines in the console output and not kill the scraper. There would also obviously need to be some message to the user that the console output has been limited.

The advantage of the second approach is that it is less upsetting to users. They still have the option of stopping the scrape themselves but they know at least that it's continuing to run even if they can't see the output.

**Comment by mlandauer** [comment]
I'm going to have a go at implementing this by putting either a wrapper process around the scraper or by piping the output of the scraper through another little script. We'll see what works.

**Comment by mlandauer** [comment]
Why does this seem to happen on a regular basis? You start working through the solution. Get stuck. Make some progress. Then, have a first working piece. Then, only then do you realise that there's another way of solving the problem. Grrr...

Another way to solve this is to put the limiting of the number of log lines in at the reading of the log lines stage. If we just don't pass any further lines up the chain then it shouldn't hog the resources. We just need to make sure that there aren't some major performance penalties to this approach.

**Comment by mlandauer** [comment]
I realised now that there is a performance penalty to the current approach of just filtering out the later log lines before they get passed up to morph. The logs still get stored in docker so the docker container can blow up to huge size. I think this is one of the things that we've been recently seeing.

So, based on this it would be a good idea to go back to one of the original ideas which was to create a wrapper process inside the docker container that limits the output to standard log. This way a nasty/careless scraper can suck up huge amounts of disk space while it's running

**Comment by mlandauer** [comment]
Definitive proof that this is going on now. A still running container for the scraper https://morph.io/danishthanvi1/my-bo_cmp_list is taking more than 88GB of space. When you go into the docker file system you can see that all of this space is pretty much taken by the json.log file at `/var/lib/docker/containers/6e510a9d41c01822a248a9f27d591317346438a6f41cc368337a8bd6329b4952/6e510a9d41c01822a248a9f27d591317346438a6f41cc368337a8bd6329b4952-json.log`
