### ISSUE TITLE
Ya tutorial needs some screenshots

### ISSUE THREAD

**Issue by mithro** [openaustralia/morph#921]
The tutorial at https://github.com/openaustralia/morph/blob/tutorial/app/views/documentation/tutorial.md would benefit from some screenshots :)

**Comment by equivalentideas** [comment]
Thanks @mithro , I think even animated gifs where appropriate could be great too.

Any other feedback on it? Was it otherwise helpful? We're still working out where to put this and whether it should be cut down/restructured in #899

**Comment by mithro** [comment]
You also need some better templates that morph uses by default, then rather then jump right into the "Writing your scraper" I would take some time to explore an existing template and explain things in the context of that. Then start doing modifications?

**Comment by mithro** [comment]
You also don't have any instructions on "confirming I have my ruby environment set up correctly". At the 
> "So far you’ve set up all your files, cloned them to your machine, and installed the necessary 
> dependencies. Now it’s time to write your scraper.
It would be good to have some commands to run which confirm that yes I've done all the above steps correctly.

**Comment by equivalentideas** [comment]
> It would be good to have some commands to run which confirm that yes I've done all the above steps correctly.

Great idea :+1:

**Comment by henare** [comment]
I'll try to integrate this feedback as I post this blog series (see https://github.com/openaustralia/morph/pull/899#issuecomment-147615998).
