### ISSUE TITLE
Manual scraper runs very slow at starting

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#923]
For the last week or so I've noticed that the time between scheduling a scraper to run manually, and it actually running, has increased dramatically. Previously it was very rare for it to take more than a minute or so to start — now delays of an hour or more are commonplace.

Is this just because it's waiting for the next free slot (and if so do manual scrapers get prioritised over scheduled ones?), or is there something else awry?

**Comment by henare** [comment]
Interesting - thanks for reporting this Tony.

After the upgrade it took quite a while to clear the queue backlog but I thought this was well done. I just checked and there are free slots now so manual runs should start immediately.

Currently there are 10 slots in total. All scraper runs, auto and manual, get put in the same queue.

Can you please let me know next time you see this?

**Comment by henare** [comment]
This issue was just reported by @paulbradshaw on Twitter: https://twitter.com/paulbradshaw/status/649481929826377728

There's currently 83 runs backlogged in the queue :disappointed:

**Comment by henare** [comment]
Ah, in the 10 slots there are 3 for the same run and 2 for another duplicate:

![selection_001](https://cloud.githubusercontent.com/assets/48945/10214934/3c26930a-6860-11e5-8834-ccf2255e4960.png)

That's definitely Not A Good Thing and might have something to do with this.

**Comment by henare** [comment]
2 hours ago was when the queue was last restarted by monit:

```
[AEST Oct  1 15:30:40] error    : 'sidekiq' total mem amount of 1794176kB matches resource limit [total mem amount>1536005kB]
[AEST Oct  1 15:30:40] info     : 'sidekiq' trying to restart
[AEST Oct  1 15:30:40] info     : 'sidekiq' stop: /sbin/stop
[AEST Oct  1 15:30:58] info     : 'sidekiq' start: /sbin/start
[AEST Oct  1 15:33:00] info     : 'sidekiq' 'sidekiq' total mem amount check succeeded [current total mem amount=1063988kB]
```

**Comment by henare** [comment]
Wow, sidekiq is still being restarted lots - about 10 times a day. I think it's related to the memory blowing out when dealing with lots of log lines (#919).

**Comment by henare** [comment]
I've stopped the queue, manually removed the jobs for duplicate run IDs, and started the queue back up.

**Comment by henare** [comment]
These were the scrapers in the queue when I checked earlier:

```
mauragio/amazon2
axelx5/cellphones
soit-sk/patenty_-_upv
rkononov/diesel_scraper
boundedrational/jobs-project_indeed_2
timgdavies/uk_contracts_finder2_ocds
rkononov/mnenie_akipress_scraper
boundedrational/jobs-project_indeed_6
montanaflynn/github-users
planningalerts-scrapers/edala
```

Unfortunately there's still 80 runs queued up so I've decided to bump the queue size up a little bit to see if that helps things (d799353dcf08e2a789e60ccb3ddfd412a387f011).

**Comment by henare** [comment]
The queue is clearing now, we're at about 50 runs.

Please comment on this issue if you see this problem again. I fear this is not fully resolved yet.

**Comment by henare** [comment]
Just noticed this happening again - 15 scrapers running with ~30 in the queue.

Looks like we'll need to spend some time fixing this sooner rather than later :unamused: I might bump up the concurrency again since we can afford to do it. I'm not really sure it will help much until we address the underlying issue.

**Comment by tmtmtmtm** [comment]
https://morph.io/tmtmtmtm/czech-chamber-of-deputies-wikidata has been at "Queued to run" for over three hours now…

**Comment by henare** [comment]
There are 20 running and ~130 queued scrapers right now with numerous duplicate jobs (#926).

**Comment by henare** [comment]
Without much intervention the queue is clearing itself now. I've deployed a change that I'm hoping will stop duplicate jobs being created (which is definitely a source of this problem).

**Comment by henare** [comment]
I'm closing this in favour of #1010. There are also other issues open for the backend problems that cause queue backlogs.

If you disagree or think things are missing from the existing issues then please extract this into a new issue that's something we can fix.
