### ISSUE TITLE
[Morph/production] Mysql2::Error: Out of range value for column 'sqlite_db_size' at row 1

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#933]
Yay, @pwalsh broke it with his massive scraper http://morph.io/okfn/opentrials-clinicaltrailsgov-data :smile: 

## Backtrace

    line 194 of [PROJECT_ROOT]/app/models/scraper.rb: update_sqlite_db_size
    line 137 of [PROJECT_ROOT]/lib/morph/runner.rb: attach_to_run_and_finish
    line 49 of [PROJECT_ROOT]/lib/morph/runner.rb: go

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/35868/faults/16725835)

**Comment by pwalsh** [comment]
@mlandauer 

Hi. Terribly sorry to bring production down. As you know (i hope), I've been on the Morph forum asking about our use case *before* we drain Morph resources, and indeed, to ensure that Morph is the right choice for our needs on a particular project.

We've been manually throttling our scraping scope for the last 2 weeks to ensure we don't consume lots of CPU/IO when we run, and I also checked about database size a week ago, including mentioning that our estimate puts the Clinical Trials scraper at 3GB:

https://help.morph.io/t/database-size-limits/153/6

So, I am sorry I broke it, but, I *did* give notice and engage that this is what we had here, and @henare seemed to think that a 3GB db would be ok.

**Comment by henare** [comment]
@pwalsh sorry for the confusion, this was actually me creating this ticket from our error reporting system. It uses @mlandauer's GitHub account so appeared to be created by him.

You definitely didn't bring production down - this error was caught and as you can see I resolved it a short time later.

We're very happy to have you testing the limits of morph.io! :smiley:
