### ISSUE TITLE
New scraper not moving out of 'queuing'

### ISSUE THREAD

**Issue by Abbie2020** [openaustralia/morph#946]
I have the same issue as #907 

I created it while there were the memory issues a couple of days ago.

**Comment by henare** [comment]
https://morph.io/Abbie2020/university_of_reading_events

**Comment by henare** [comment]
>I created it while there were the memory issues a couple of days ago.

Because the disk space was exhausted the background job to create the repository, etc. wasn't created. I manually created the job on the console and it's now fixed.
