### ISSUE TITLE
Feature request - If a scraper received no data for x days, I get an email?

### ISSUE THREAD

**Issue by LoveMyData** [openaustralia/morph#947]
Feature request if a scraper received no data for x days, I get an email?

This will likely notified the owner that the scraper not getting any error however no data received.

Likely cause is the page is working but formatting need adjustment or something.......

**Comment by henare** [comment]
I think morph.io would have trouble reliably doing this because it doesn't know about your data.

However you could do this in your scraper by raising an exception if you've got no data. Does this solve your problem @LoveMyData?

**Comment by LoveMyData** [comment]
I don't think raising an exception will work, no DA over the weekend and time like long weekend etc

If the variable can be set by the user per scraper, can we do something like

if (Now - last_scraped_date) >= variable then send trigger email ?

**Comment by equivalentideas** [comment]
> I don't think raising an exception will work, no DA over the weekend and time like long weekend etc

@LoveMyData could you tell this statement not to raise an error if it it's a Saturday, Sunday or Monday?

**Comment by henare** [comment]
>I don't think raising an exception will work, no DA over the weekend and time like long weekend etc

Yeah, I meant check to see how long it's been since the scraper collected data and raise an error if it's over your threshold.

>if (Now - last_scraped_date) >= variable then send trigger email ? @henare 

Exactly. If it's over a threshold just raise an error and then morph.io will automatically send an email saying your scraper is broken.

**Comment by LoveMyData** [comment]
yes @henare, as long as there is threshold to set and no data received.

**Comment by henare** [comment]
Cool. I'm closing this since it seems better to do this in your scraper and not in morph.io itself.

**Comment by LoveMyData** [comment]
Ooo. I didnt mean to code it in my scraper but a feature from morph.io
sorry for the confusion.
