### ISSUE TITLE
How do I update the “settings” section of my scrapers settings?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#959]
On my scrapers settings page I can see a button to update _Secret environment variable_ and the _Webhooks_, but not the top _Settings_ auto run setting.

![screen shot 2016-02-23 at 12 00 19 pm](https://cloud.githubusercontent.com/assets/1239550/13238275/d2fc6f2a-da25-11e5-8605-ab5fea64ac54.png)

If I make changes to multiple settings and then hit the wrong button will I lose my changes?

This is really confusing.

Here are a few solution ideas:

1. provide a signifier to which button maps to which setting by adding text to the labels “Update settings and environment variables”, “Update webhooks”?
2. add a button to update the top _Settings_ section so that the proximity of each button to the section signifies that it updates that section.
3. have one button that updates all the settings?
4. auto update the settings as they are changed and remove the button all together?

Options 1 and 2 seem like they could be helpful, but the problem of update the wrong section and loosing you data still seems like a problem.

Option 3 seems quite familiar and it's clear that the one button updates all the settings so it's unambiguous what happens to all my changes when I hit it.

Option 4 seems nice, and it's what Github do, but like a progressive enhancement on 3.

**Comment by henare** [comment]
I think the hierarchy of this form is out of whack - Webhooks and Secrets are subsections of Settings. So I'm going to implement Option 2.

**Comment by equivalentideas** [comment]
> I think the hierarchy of this form is out of whack - Webhooks and Secrets are subsections of Settings.

I'm not sure what you mean by that. Maybe a little sketch or something of how you think that'd work would help?

**Comment by henare** [comment]
Settings is an H3 and the nested headings are also H3. They should be H4.

Then it's clear this is all one form, rather than the current 3 (?) forms.

**Comment by equivalentideas** [comment]
> Then it's clear this is all one form, rather than the current 3 (?) forms.

That sounds much more sensible. Is that like the solution 3 above?

> have one button that updates all the settings?

**Comment by henare** [comment]
Ah, that's the confusion then - I meant option 3 in [my comment above](https://github.com/openaustralia/morph/issues/959#issuecomment-187491623) :-/

**Comment by equivalentideas** [comment]
That'll do it ;-)
