### ISSUE TITLE
The necessary /tmp/pids folder is in .gitignore

### ISSUE THREAD

**Issue by snoblenet** [openaustralia/morph#967]
Sometimes Sidekiq will fail to create this folder, leaving the user to do some manual troubleshooting to get started.

My first thought it is to just update .gitignore, and I'd be inclined to just list the excluded subdirectories of /tmp rather than using the negation syntax.

Let me know if you want me to do this.

**Comment by henare** [comment]
Thanks for logging this @snoblenet :sunny: I don't quite understand what the problem is. Can you please clearly state the problem and the steps to reproduce?

**Comment by snoblenet** [comment]
Sure.

1. User follows the installation steps detailed in the Read Me
2. User types `bundle exec dotenv foreman start`
3. Some users then get a `No such file or directory` error because Sidekiq cannot find a `tmp/pids` directory to store its PID files, and sometimes it fails to just create the required directory itself
4. The user hunts around, eventually types `makedir /tmp/pids`, and is relieved to find that `bundle exec dotenv foreman start` now works just fine

I'm proposing we include the `/tmp/pids` directory (but not the files it contains) in the git repository so no users encounter Steps 3 and 4.

Here's [discussion of the issue on StackOverflow](http://stackoverflow.com/questions/26006496/sidekiq-does-not-generate-sidekiq-pid-file-on-heroku-using-with-redistogo).

**Comment by henare** [comment]
Thanks for that! :evergreen_tree: I'd not encountered this before so it's really good to have this clear description.

>I'm proposing we include the /tmp/pids directory (but not the files it contains) in the git repository so no users encounter Steps 3 and 4.

Sounds good to me :+1:
