### ISSUE TITLE
Backed up queue - 20 processes running but only 9 containers running

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#992]
We've got over 200 runs in the queue right now. So the 20 processes are all churning away, however only 9 containers are currently running. What's going on?

**Comment by henare** [comment]
Something weird is happening. For example, [this scraper](https://morph.io/kelpenhagen/Bills_Introduced_in_NSW_Parliament) that has recently taken just 4 minutes to run is currently sitting at 7 hours run time. Its container is stopped (it ran for 1 minute) and it's just really slowly streaming the logs off now (like 1 line every 4 seconds or so).

My guess is that another scraper is streaming shitloads of logs off and that's tying up the sidekiq process so all other scrapers are taking ages to stream their logs off too.

**Comment by henare** [comment]
`jflavan/pitchfork_review_data` is currently sitting at over 62,000 log lines. `Charrod/CSGOTeamBotScraper` is over 10,000.

**Comment by henare** [comment]
`jflavan/pitchfork_review_data` has been in the queue for a day but the run started 3 days ago. Runs are killed after 24 hours but the process that streams logs off isn't I guess.

**Comment by henare** [comment]
https://github.com/jflavan/pitchfork_review_data/blob/master/scraper.py was forked from ScraperWiki over a year ago and has presumably been running OK since. Looking at the code it seems like the site may have been updated and the scraper is now just endlessly looping, fetching the same page over and over and outputting a line every time. That's really not a good thing to do to that site (and to morph.io).

I'm going to manually delete the run from the queue, switch off autorun and notify the owner.

**Comment by henare** [comment]
Just deleting that one hasn't done much. https://morph.io/kelpenhagen/Bills_Introduced_in_NSW_Parliament is still glacially streaming logs.

**Comment by henare** [comment]
https://morph.io/kelpenhagen/Bills_Introduced_in_NSW_Parliament has finished now but its last run says it only took 3 hours. That doesn't tally with

>For example, this scraper that has recently taken just 4 minutes to run is currently sitting at 7 hours run time.

I wonder why?

**Comment by henare** [comment]
We're down to about 150 runs in the queue so it seems to be clearing.

I'm going to close this issue. I've extracted what I think is the underlying issue into #993.

**Comment by tmtmtmtm** [comment]
FWIW I've seen 4 separate 'Pitchfork' scrapers all churning away for forever sending so much log data that even trying to load the page has brought my laptop to a standstill…

**Comment by henare** [comment]
Today we're back to 215 in the queue. This stinks.

**Comment by henare** [comment]
Right now there are just 4 containers running. That means that there's 16 background workers just streaming logs of stopped containers.

**Comment by henare** [comment]
Well one mystery solved:

>https://morph.io/kelpenhagen/Bills_Introduced_in_NSW_Parliament has finished now but its last run says it only took 3 hours. That doesn't tally with
>
>    For example, this scraper that has recently taken just 4 minutes to run is currently sitting at 7 hours run time.
>
>I wonder why?

It's because the job was _queued_ 7 hours ago but only started 4 hours after that, making a 3 hour run time.

**Comment by henare** [comment]
I've been monitoring this throughout the day and we're not making a lot of progress getting through the backlog (it's at 150 now).

I've been observing only a few containers running while all 20 concurrent jobs are running. This means the bulk of jobs are just finishing off runs (streaming logs, moving database files, etc.).

Sidekiq is always pegged at 100% CPU and only runs on one of the 8 cores. So I've created another process to see if that takes some of the load off. If that works then we can look at making that permanent.

**Comment by henare** [comment]
>So I've created another process to see if that takes some of the load off. If that works then we can look at making that permanent.

That definitely seems to have helped, the queue is now clear. I'm going to set it so production has 2 sidekiq processes.

**Comment by henare** [comment]
While I was investigating why one of the processes was running at 100% CPU I discovered that there were 2 runs for the same scraper in its list of jobs. Could this be the cause?

**Comment by henare** [comment]
>That definitely seems to have helped, the queue is now clear. I'm going to set it so production has 2 sidekiq processes.

As I feared this only shifted the problem temporarily. We're back to 18 in the queue.

**Comment by henare** [comment]
I've extracted this issue into #997.
