### ISSUE TITLE
Purge old log lines

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#999]
Our log lines table is a little large:

```
> LogLine.count
 => 99230256 
> 
```

Since only the output of the last run is available, can we just purge all log lines for runs that aren't the most recent?

**Comment by mlandauer** [comment]
I need to do this as I'm about to make a change that requires doing a migration on the log_lines table. Without doing this first, it could take a *very* long time.

Initially, I'll just make a rake task to do the cleanup and then we can think whether we want to do something that does this cleanup as we go along
